### ISSUE TITLE
Switch to Admin

### ISSUE THREAD

**Issue by lodarmayarder** [PhoenixPE/PhoenixPE#10]
﻿

Checklist
---------
- [X] I performed a search in the issue tracker to see if my suggestion has already been asked/answered by somebody else.

**Describe the solution you'd like**
A function to create an administrator account and thus log in for certain software.
Switch to admin.
Thanks in advance

**Describe why you believe your suggestion would benefit the project and members of the community at large**
 launch some software, install some drivers...

**Describe alternatives you've considered**
None

**Comment by homes32** [comment]
Would you mind expanding on your reasons for needing "Admin" in WinPE?

I'm not wholly opposed to adding it at some point, however in 20+ years for building, writing, and using WinPE in the field, I have never once needed to run as anything other then SYSTEM. A list of software, etc. would help with testing and prioritizing this enhancement.

I'll start.

Software "Known" to need run as "Admin"
- TeamViewer (Alternatives available)
- Download files in IE6 (I will never add Internet Explorer support in PhoenixPE, so this point is moot...)

**Comment by lodarmayarder** [comment]
Cette fonctionnalité peut-être utilisé pour l'usage de certain drivers. 

En l'état le logiciel FreeOTFE et toutes les autres variantes ne peut monter de disque chiffré. 

D'avance merci

**Comment by homes32** [comment]
Support for login as Admin was added in commit cf0f1dd134df956d70cb806f4919db5b8f50e518
