### ISSUE TITLE
Link to release page just returns to Main

### ISSUE THREAD

**Issue by rrlindsey** [PhoenixPE/PhoenixPE#100]
﻿

Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
﻿

**Describe what is happening**
A clear and concise description of the issue you are experiencing. 
Exactly what the title says -- release link returns to Main page
**To Reproduce**
Step-by-step instructions on how to reproduce the behavior:

**Expected behavior**

**Screenshots/Logs**
If applicable provide any error messages, log files, screenshots, scripts, etc. that may be helpful for troubleshooting or further explain your issue.

**Comment by PCAssistSoftware** [comment]
Just click on Releases in right hand column?...?

![image](https://github.com/user-attachments/assets/d8cc9620-608c-487c-82fb-1125b85e48e7)

**Comment by homes32** [comment]
Resolved.
