### ISSUE TITLE
Escape/unescape script macro needed

### ISSUE THREAD

**Issue by Mikka-TheOne** [PhoenixPE/PhoenixPE#103]
In the _Utilities_ section, PEBakery offers the handy _String Escaper_ tool (maybe an idea to also access it via the _Toolbox_ in future).

Now I need to write a varying JSON string to the registry. There are mainly lots of double quotes that need to be escaped first.
How can I realise this most easily?

I was thinking of something like:
```
StrFormat,Replace,"unescapedContent.json","\u0022","#$q","%escapedContent%"
StrFormat,Replace,"%unescapedString%","\u0022","#$q","%escapedString%"
// etc.
```
Unfortunately that won't work.

Best would be a proper macro to get the output of the _String Escaper_ tool (primarily `#$p, #$q, ##`).

**Comment by Mikka-TheOne** [comment]
I've got an idea to do the conversion via batch script. However, in the past importing external data into variables was always quite tricky (ini file workaround). Is there a simpler way on how to get an external file's content as script variable?

**Comment by homes32** [comment]
an intermediate .ini file is still the easiest way.

That's what I'm doing with some PhoenixAPI commands, running the bulk of the operations in autoit, powershell or another executable and writing to a .ini file to read back in to a variable.

**Comment by Mikka-TheOne** [comment]
I was able to work around my initial problem by handling it outside _(cmd)_ of the script.
Since my JSON processing also takes place there _(jq)_, this was the preferred option.
From this point of view, this topic has become irrelevant as static strings can be converted just as well with _String Escaper_.

**Comment by Mikka-TheOne** [comment]
> an intermediate .ini file is still the easiest way

There are hitches, however. An ini file must meet some criteria to be properly processed by `IniRead`.
CR-LF line breaks and one following the intended line. Also longer section names seem to work better, `[JSON]` is too short.
I didn't check for encoding issues, but UTF-8 should be fine.

**Comment by homes32** [comment]
>From this point of view, this topic has become irrelevant as static strings can be converted just as well with String Escaper.

Closing as this would require changed in the PEBakery engine itself before I could even consider adding a marco to PhoenixPE.
