### ISSUE TITLE
Updates for 051-StartIsBack++.script, AttributeChanger.script

### ISSUE THREAD

**Issue by Mikka-TheOne** [PhoenixPE/PhoenixPE#104]
I came across two scripts that need updates.

### Shell: 051-StartIsBack++.script

Line 44 has changed:
`%DownloadURL%=https://startisback.sfo3.cdn.digitaloceanspaces.com/StartIsBackPlusPlus_setup.exe`

Line 47 also ought to be updated, e.g. `%SupportedVer%=5.9.20.3594`

### Applications, System Tools: AttributeChanger.script

Lines 46, 47 have changed:
```
%aLangMap-Strings%=Brazilian|1|Czech|2|Danish|3|French|4|German|5|Hungarian|6|Italian|7|Korean|8|Dutch|9|Polish|10|Spanish|11|Swedish|12|Turkish|13
%aLangMap-Docs%=Brazilian|1|Czech|2|Danish|3|English|4|French|5|German|6|Hungarian|7|Italian|8|Korean|9|Dutch|10|Polish|11|Spanish|12|Swedish|13|Turkish|14
```
And accordingly to line 277:
`cmb_Language=English,1,4,15,126,150,21,Brazilian,Czech,Danish,Dutch,English,French,German,Hungarian,Italian,Korean,Polish,Spanish,Swedish,Turkish`

**Comment by homes32** [comment]
updated. Thank you!
