### ISSUE TITLE
 Korean IME did not work

### ISSUE THREAD

**Issue by Zerojinny** [PhoenixPE/PhoenixPE#108]
Korean IME did not work in windows 10.0.18363 or later.

So i tested someting to work , i found a solution.

I added a line below and now it works.

If,%SourceVer%,BiggerEqual,10.0.18363,RegDelete,HKLM,"Tmp_Software\Microsoft\Input"

**Comment by homes32** [comment]
Interesting. Thanks for the tip!

**Comment by homes32** [comment]
Removing the Input key did not resolve the issue in my tests. After testing it was found that re-running the IME script after the build was complete would correct the issue with the toolbar/tray not starting. Upon analyzing the it appears the keyboard layout was and language profile was being modified.

![image](https://github.com/user-attachments/assets/77dd0a8d-5ab5-42f9-963a-6f9580794bd1)

Issue resolved in https://github.com/PhoenixPE/PhoenixPE/commit/80685ec84e686fb8517a9c5ec33f8877840fa943

Keyboard configuration in Localization script needed to take place before the IME script is run.

**Comment by Zerojinny** [comment]
Thank you for your hard work.
i'm looking forward to the next version.
