### ISSUE TITLE
Question: saving selections

### ISSUE THREAD

**Issue by kzshantonu** [PhoenixPE/PhoenixPE#109]
Hi,

Successfully made my perfect custom PE. Thanks for the hard work. I'd like to save my selections while deleting all cache and temp files. Which directory do I have to keep to only keep my selections and settings?

**Comment by homes32** [comment]
What selections and settings are you referring to specifically?

the script selections (enabled/disabled) and interface selections are stored in the scripts themselves and will not reset if you use the "Nuke" option. They will only reset if you download a new script or use the "Restore Defaults" button on  each script interface.

If your interesting in saving script selections/settings though update check out this issue:  How to export/import project settings ? #13 

If you simply want to reclaim disk space by clearing out cache/temp after a build you can delete the following folders:

Temp files from building
`<PhoenixPE>\Workbench\PhoenixPE\Temp`

Downloaded programs cache - keep in mind some program customization such as PENetwork config are also stored here.
`<PhoenixPE>\Workbench\PhoenixPE\Programs`

Build directory
`<PhoenixPE>\Workbench\PhoenixPE\Target`

**Comment by kzshantonu** [comment]
That's exactly what I wanted to know. Thanks
