### ISSUE TITLE
Converting existing scripts from Win10XPE to work with PhoenixPE?

### ISSUE THREAD

**Issue by PCAssistSoftware** [PhoenixPE/PhoenixPE#111]
Hi

I am a long (very long) time user of Win10XPE and all the predecessors, I now want to start making use of PhoenixPE as it works really well and is updated regularly.

Some of the scripts I use with Win10XPE are not currently available with PhoenixPE, so I tried just dropping them in, but the build then fails with errors such as below.  Is there a guide or instructions somewhere on how to easily port the scripts across? or do they have to be completely re-written?  

Extracts from logs below from four different scripts I have tried:

**DISM Tool**

<Errors>
- [1] Error in script [DISM Tool] (PhoenixPE\Applications\DISM_Tool_XPE.Script)
[Error] Macro - Invalid command [EchoExtended] (If,Not,ExistFile,%GTarget_Win%\Microsoft.NET\dotnetver.exe,EchoExtended,"You Need To Enable .Net Framework To Run %ProgramTitle%",,,Message,2,Exit) (Line 42)

----

**MiniTool Partition Wizard Free 9.1**

<Errors>
- [1] Error in script [MiniTool Partition Wizard Free 9.1] (PhoenixPE\Applications\MiniTool Partition Wizard Free 9.1_XPE.Script)
[Error] ShellExecute - An error occurred trying to start process '%GTools%\7z.exe' with working directory 'Z:\PhoenixPE'. The system cannot find the file specified. (ShellExecute,Hide,%GTools%\7z.exe,"x #$q%GTemp%\%ProgramFolder%\%SetupFile%#$q -y -o#$q%GTemp%\%ProgramFolder%\%ProgramFolder%#$q") (Line 73)

----

**UnlockIT**

<Errors>
- [1] Error in script [UnlockIT] (PhoenixPE\Applications\UnlockIT_XPE.Script)
[Error] ShellExecute - An error occurred trying to start process '%GTools%\7z.exe' with working directory 'Z:\PhoenixPE'. The system cannot find the file specified. (ShellExecute,Hide,%GTools%\7z.exe,"x #$q%GTemp%\%ProgramFolder%\%SetupFile%#$q -y -o#$q%GTemp%\%ProgramFolder%\%ProgramFolder%#$q") (Line 96)

----

**PC Assist Software (my own script containing various tools I created for PE from https://www.pcassistsoftware.co.uk/free.html)**

<Errors>
- [1] Error in script [PC Assist Software] (PhoenixPE\Applications\ON TEST\PC_Assist_Software_XPE.Script)
[Error] Macro - Invalid command [EchoExtended] (If,Not,ExistFile,%GTarget_Win%\Microsoft.NET\dotnetver.exe,EchoExtended,"You Need To Enable .Net Framework To Run %ProgramTitle%",,,Message,2,Exit) (Line 54)

Thank you - and great work!!

Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

**Comment by PCAssistSoftware** [comment]
Closed - as have now worked out how to create new scripts that work with Phoenix - will upload them to forum shortly :)

**Comment by homes32** [comment]
lol, well that didn't take you long! :)

Your best friends are going to be:
https://github.com/PhoenixPE/PhoenixPE/wiki/PhoenixAPI
and
https://github.com/PhoenixPE/PhoenixPE/wiki/ProjectVars

if you haven't  already found them.

2 of your errors are related to the silly EchoExtended command. this will have to be re-written with a regualr Echo command
the 2 with 7z you will need to replace
```
ShellExecute,Hide,%GTools%\7z.exe,"x #$q%GTemp%\%ProgramFolder%\%SetupFile%#$q -y -o#$q%GTemp%\%ProgramFolder%\%ProgramFolder%#$q"
```
with
```
7z,"x #$q%ProjectTemp%\%ProgramFolder%\%SetupFile%#$q -y -o#$q%ProjectTemp%\%ProgramFolder%\%ProgramFolder%#$q"
```

**Comment by PCAssistSoftware** [comment]
Yes once I started playing around with it I found I spent all day working on it (and quite enjoying it to be honest)

Thanks for your response, and thanks for all the great work on the project.

P.S. If you need any testers when you look at trying to get it working with 24H2 just let me know, always on hand for some testing :)
