### ISSUE TITLE
When I click on Download Source ISO I get a confirmation message... Launching Fido, then it closes, nothing is downloaded

### ISSUE THREAD

**Issue by cyberneticus2024** [PhoenixPE/PhoenixPE#112]
![Fido](https://github.com/user-attachments/assets/4c5d70ca-b6e3-43b9-8e5d-e0f1225f4d24)

Checklist
---------
- [ ] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [ ] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
﻿

**Describe what is happening**
A clear and concise description of the issue you are experiencing. 

**To Reproduce**
Step-by-step instructions on how to reproduce the behavior:

**Expected behavior**

**Screenshots/Logs**
If applicable provide any error messages, log files, screenshots, scripts, etc. that may be helpful for troubleshooting or further explain your issue.

**Comment by cyberneticus2024** [comment]
[SystemLog_2024_11_22_002330.txt](https://github.com/user-attachments/files/17852765/SystemLog_2024_11_22_002330.txt)
[BuildLog_2024_11_22_002137_Source_Config_-_Button__btn_GetISOFido_.txt](https://github.com/user-attachments/files/17852767/BuildLog_2024_11_22_002137_Source_Config_-_Button__btn_GetISOFido_.txt)

**Comment by PCAssistSoftware** [comment]
Just tested and working fine here, after clicking Yes (Da) on the dialog you show above I then see this dialog, can select Windows 11 and click Continue, then select release and click Continue, then select Edition and click Continue, then Language and Continue, then Architecture and then click Download and it starts to download the file in my browser.

check you don't have anything on your computer that could be blocking it e.g. A/V etc

![image](https://github.com/user-attachments/assets/c96844f4-57c4-4f98-8e0c-9a15ddecb79a)

**Comment by cyberneticus2024** [comment]
Fido.avi
<https://drive.google.com/file/d/1t6a8esaxsVREnFhLQKN87VNjECg8XknR/view?usp=drive_web>


În vin., 22 nov. 2024 la 01:06, Darren Rose ***@***.***> a
scris:

**Comment by homes32** [comment]
Your log tells you what the problem is:

```
[Error] WebGet - Cannot write into [C:\WINDOWS 11\PhoenixPE-2024.09.13-x64\Workbench\PhoenixPE\Temp\Fido.ps1.lzma], 
[C:\Windows] is a write protected directory (WebGet,%FidoURL%,"%ProjectTemp%\Fido.ps1.lzma") (Line 338)
```

Try renaming `C:\WINDOWS 11` to `C:\WINDOWS_11` or something similar to remove the space from the path.
