### ISSUE TITLE
"Halt - ERROR: You must specify the path to AutoBackup source files" and "Echo - Warning: Version mismatch. WinRE is not the same version as the source image. This may result in build failures."

### ISSUE THREAD

**Issue by KonstiP** [PhoenixPE/PhoenixPE#113]
Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
After downloading and sourcing the ISO and checking the apps and tweak I want, I started the build and after some minutes it HALTs and gives me this error codes. I've tried multiple different ISOs both the downloadable though PheonixPE and manually downloaded and i get the same error every time.

[BuildLog_2024_11_29_212411_Project_PhoenixPE.txt](https://github.com/user-attachments/files/17963036/BuildLog_2024_11_29_212411_Project_PhoenixPE.txt)
![image](https://github.com/user-attachments/assets/15037c82-da7f-4486-a627-f56ea52554dc)

**Comment by homes32** [comment]
The issue is just what the error message says. You didn't provide the source files for the AutoBackup script. AutoBackup is not free. you need to purchase a license and then the author gives you a link where you can login and download the installer. It's not something PhoenixPE can do for you.

**Comment by KonstiP** [comment]
Oh wow Ok thanks. That was less of an issue than I thought. Guess I didn't know how to read the error correctly. Thank you very much.
