### ISSUE TITLE
Location Of Script Files

### ISSUE THREAD

**Issue by vshanecurtis** [PhoenixPE/PhoenixPE#115]
Hello,

I am unable to locate the directory containing the script files.  Please advise.   Also I am unable to log on to the forum.  I have tried several times to create an account.  Could you please pass this issue to the correct people?

Regards,
Shane Curtis

**Comment by homes32** [comment]
The project's script files are located in `<PhoenxiPE>\Projects\PhoenixPE`
your custom script files go in `<PhoenxiPE>\Projects\MyApps`

you can also right-click on any script in the tree view and choose "Open Script Folder" to navigate to the directory of the script.

**Comment by homes32** [comment]
The forum signin is very sensitive to cookies, so make sure you turn off any ad/popup blockers and accept cookies.
