### ISSUE TITLE
Partition Assistant Does Not Run From PE.  

### ISSUE THREAD

**Issue by vshanecurtis** [PhoenixPE/PhoenixPE#116]
Checklist
---------
- [X] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [X] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
I created a PE build which include Partition Assistant.   Attempted to run it from PE environment using both desktop shortcut and taskbar icon and both options produce the same error.  Script was executed during build process.  Examination of the ISO shows no directory was created for AOMEI Partition Assistant install files.

1. Applications/Disk Management
2. Click on AOMEI Partition Assistant.  I tried multiple variations of install options without success.  Also tried keeping the default selections from the treeview as well as just the apps I wanted.  Same result.
3. Execute Build

**Expected behavior**
I expected AOMEI Partition Assistant to run when selected from the PE environment.
**Screenshots/Logs**
If applicable provide any error messages, log files, screenshots, scripts, etc. that may be helpful for troubleshooting or further explain your issue.

**Comment by homes32** [comment]
It's working fine on our end, so I suspect an error with your build or AV interference, however, you didn't attached your log so we have no idea of knowing what that might be....

**Comment by vshanecurtis** [comment]
Mr. Holmgren,

Thanks for your timely response and answering my questions.  The forum sign in process is entirely too complicated, in my opinion.  The "puzzle" you have to solve to get registered is unnecessary.  There are far simpler ways to validate someone that are just as effective.  As for the issue with Partition Assistant, the problem is solved. Something was going on with my computer.  Other things were going sideways that made no sense so I decided to restore my system from a backup.  Once I did that, things started working again.  I do have a suggestion for a program addition.  Adding an option to call Rufus or another similar program after building the ISO would be very nice.  Winbuilder had this option.  It was very helpful to be able to call Rufus directly from the development environment.

Regards,
Shane Curtis
________________________________

**Comment by homes32** [comment]
> I do have a suggestion for a program addition. Adding an option to call Rufus or another similar program after building the ISO would be very nice. Winbuilder had this option. It was very helpful to be able to call Rufus directly from the development environment. 

Already implemented:
![image](https://github.com/user-attachments/assets/57becd07-0988-47dd-8516-cdb3b522d214)
