### ISSUE TITLE
[Help] How to force an update to an application ? 

### ISSUE THREAD

**Issue by captain-majid** [PhoenixPE/PhoenixPE#12]
Hi there,
Can I force an update to an application, or provide an alternate source to it ?
I want to get the newest version of Open-Shell, but every time I delete the cache, I get v4.4.170, which is old, I think this version is hardcoded inside `050-OpenShellMenu.script` bc even when I'm disconnected from the Internet, it returns. If you can direct me on how to open this .script file to include the new files that would be nice too.

**Comment by homes32** [comment]
Hello!

In general *Most* application download links can be modified to use a new version by updating the `%ProgramVersion%` variable. the format will vary from application to application but you can get a good idea by looking at the download URL/version on the software website. You can make the modification by opening the .script file in a standard text editor or by using the "Pencil" icon in PEBakery and selecting "Edit Script Source". (you may need to setup a text editor first in the PEBakery > Settings > Interface tab and select the Custom Editor checkbox under the External Code Editor section.)

Example:
```
[Main]
Title=7-Zip
Author=Homes32
Level=5
Version=1.2.0.0
Description=(v22.01) 7-Zip is a free and open-source file archiver capable of reading and writing many archive formats.
Date=2022-08-18
Selected=False
Mandatory=False

[Variables]
%ProgramFolder%="7-Zip"
%ProgramExe%="7zFM.exe"
// UPDATE THE FOLLOWING LINE TO THE NEW VERSION
%ProgramVersion%=2201
%DownloadURL86%=https://www.7-zip.org/a/7z%ProgramVersion%.exe
%DownloadURL64%=https://www.7-zip.org/a/7z%ProgramVersion%-x64.exe
```

For Open-Shell, you are correct in thinking that the binaries are encoded inside the script itself. There are two reasons for this:
1. Open-Shell using some goofy packaging of .msi files inside a proprietary setup exe, so its difficult to extract automatically.
2. Its the default start menu, so I wanted it make sure you could always build a working PE with the default settings, without requiring an internet connection.

you can update the installers yourself though. v4.4.170 is the current STABLE release, however there are some pre-releases available on the open-shell github page. I generally don't like including pre-release versions in the PhoenixPE releases unless I have had time to test them properly or the changes are significant enough that they solve an important issue. 

1. Open PEBakery and select the Open-Shell script
2. Click the Pencil icon and select *Edit Script Properties*
3. On the Attachments tab select the Open-Shell folder and extract the Open-Shell-x64.7z and Open-Shell-x86.7z archives
4. Open each archive with 7Zip and update the Open-Shell binaries (`StartMenuHelperL10N.ini`, `StartMenuL10N.ini`, `StartMenuDLL.dll`, `StartMenu.exe` are the most important). Can be found in C:\Program Files\Open-Shell\ if you have open-shell installed on your PC.
5. re-attach the .7z back to the script, overwriting the originals. Make sure you keep the exact same name and change the PEBakery compression from `Deflate` to  `None` for compression when attaching.
6. Update `StartMenuHelper32.dll` and `StartMenuHelper64.dll` (can be found in C:\Windows\System32 if you have open-shell installed on your PC). overwrite the existing attachments and use LZMA2 as the compression.

I'll take a look at the latest pre-release and see if it's stable enough to include. if so I should be able to commit an updated script in a few days.

**Comment by homes32** [comment]
The latest open-shell nighty's include some good fixes for Win11 sources and seem to be stable enough so I've updated the script in the master branch. You can download it from [here](https://github.com/PhoenixPE/PhoenixPE/blob/master/Projects/PhoenixPE/Shell/050-OpenShellMenu.script) and replace the current script. I've also rewrote the extraction routines to make future updates as simple as replacing the attached setup.exe and updating the `%ProgramVersion%` string.
