### ISSUE TITLE
How to add commands to PEcmd.ini ?

### ISSUE THREAD

**Issue by captain-majid** [PhoenixPE/PhoenixPE#14]
I'm trying to add a command to the start of `pecmd.ini`, but it doesn't run, I don't want to wait for all the initializations to finish, want to give the user the option to run some things quickly, is this the right way to do it ?

Also, a bit off-topic, but can I make 2 editions of PhoenixPE, one light/quick and one full, and put the 2 indexes in a single boot.wim, giving the user the option to start which one he likes, while taking the advantage of having partially identical indexes compressed together to save space ?

```cs
// This is the main PECMD configuration file for PhoenixPE
// It is launched by: RegWrite,HKLM,0x1,"Tmp_System\Setup","CmdLine","Pecmd.exe Main #$pWindir#$p\system32\Pecmd.ini"

EXEC %WinDir%\System32\menu.cmd -----------------------------------> this line didn't work

LOGS Pecmd.log
LOGO %WinDir%\web\wallpaper\Windows\img0.jpg

// Check to see if we should login as Admin
REGI #HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\AutoSwitchToAdmin,AutoSwitchToAdmin
FIND $%AutoSwitchToAdmin%=0x1, TEAM SwitchToAdmin | EXIT

TEXT System configuration, Please Wait...#0xFFFFFF L59 T39 $20*
Init
AudioInit
PreShell
Shortcuts
ShellInit
PostShell
NetInit
WAIT 3000
EXIT
```

**Comment by homes32** [comment]
```EXEC %WinDir%\System32\menu.cmd -----------------------------------> this line didn't work```
No reason that shouldn't work.

first thing you'll want to do is put you command **after** the `LOGS Pecmd.log`  command.

then you will be able to look at what if any error messages `X:\Windows\System32\PECMD.LOG` has for your EXEC command to see where things are going wrong. 

Also keep in mind that the `LOGO` command is basically throwing up a splash screen that covers up everything, so you will also need to comment out that line if you want to interact with things before the shell starts or your cmd window will be hidden behind the overlay.

As for the dual image .wim, I've never tried it but again, but [others have done similar](https://rmprepusb.com/tutorials/016-boot-to-a-winpe-wim-file-with-multiple-images/) and been successful.
