### ISSUE TITLE
How to add more forensic programms to PhoenixPE?

### ISSUE THREAD

**Issue by WelMar** [PhoenixPE/PhoenixPE#19]
In computer-forensics there are several important standard programs that would fit perfectly into PhoenixPE.
How can more programs be added to a portable Windows, build with PhoenixPE

**Comment by homes32** [comment]
You are free to create your own application scripts to include any programs you wish! 

The easiest way to start is by studying one of the existing scripts and adapt it to your needs. There is also documentation available to help you understand the script language and macros available.

- [PEBakery Script Engine Documentation](https://github.com/pebakery/pebakery-docs)
- [PhoenixPE API](https://github.com/PhoenixPE/PhoenixPE/wiki/PhoenixAPI)

If you get stuck feel free to post in one of the [Community Forums](https://github.com/PhoenixPE/PhoenixPE#support) for advice. Happy scripting!
