### ISSUE TITLE
Additional Files

### ISSUE THREAD

**Issue by anffna** [PhoenixPE/PhoenixPE#20]
Hi guys! I've been following your work since "WIN10PE_SE", great work, both! So the "Components\Additional Files" script is not working with Boot.wim, it just saves to the root of the cd. I had to modify the code for it to work. I'm not a programmer but it seems that the code only points to the root of the CD. Thank you for your attention!

**Comment by homes32** [comment]
can you provide a log or any further information, this seems to be working correctly on my system.

**Comment by anffna** [comment]
So since your system is working I tried again, this time I just clicked on the field "Additional In Ram/Boot.wim Files\x64" because the folders have the same name in both options, when I look in the "Targed" folder everything looks like ok but at the end of the construction everything was in the root of the CD again.... I modified the code, where there was %fb_MediaFilesX64% I changed the path ...\x64 to ...\MediaFilesX64 it worked... Thanks for your attention , homes32!

**Comment by homes32** [comment]
Well, it does seem silly to default both to the same directory. I've made some changes for the next release that should help avoid confusion/issues in the future
- Defaulted the paths boxes to empty
- If you use the "Browse" button on an empty path box it will create a sub directories to separate boot.wim and CD/USB so the files are not copied to both paths.

**Comment by anffna** [comment]
Hi Man, thank you again for your attention! It's good to have WIN10PE_SE back from the ashes!
