### ISSUE TITLE
Tweaks\Mouse Settings

### ISSUE THREAD

**Issue by anffna** [PhoenixPE/PhoenixPE#21]
Hi guys! So, the "Tweaks\ Mouse Settings" script is not working with the mouse lock, the other fields are ok. Thank you for your attention!

**Comment by homes32** [comment]
dumb mistake, its looking at the wrong checkbox value. :)
change line #75 to `If,%cb_TurnOnClickLock%,Equal,True,BitSet,%PrefMask%,2,7,8`

**Comment by anffna** [comment]
Working fine now. Thank you, [homes32 !

**Comment by homes32** [comment]
my pleasure, thanks for taking the time to report!
