### ISSUE TITLE
Desktop icons display a black square

### ISSUE THREAD

**Issue by anffna** [PhoenixPE/PhoenixPE#22]
Hi Man, it's me again....So when I restart explorer the desktop icons display a black square. I had to delete the key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Icons\<%windir%\System32\Transparent.ico>", despite the transparent.ico file existing in the folder... Once again, thanks for the attention!

**Comment by homes32** [comment]
This ones been bugging me on an off for awhile. Windows has some funny issues when it comes to fully transparent icons, hopefully this fixes the issue.

**Comment by anffna** [comment]
Again, thanks man, for the attention!
