### ISSUE TITLE
No network connection WIN11 22621.382/525 UEFI

### ISSUE THREAD

**Issue by VanFlusen** [PhoenixPE/PhoenixPE#23]
I have done many builds on 2 different UEFI-PCs using PhoenixPE 2023-01-30 and WIN11 22621.382/525.
It works very well.
The problem: no network connection is established when booting on UEFI-PCs.
The network connection is available on legacy BIOS-PC and VM.
The same symptoms with ChrisR/Win10XPE with 22621.382/525.
(22000.194/318 network connection works on Win10XPE)

I clean installed Win11 Pro on a UEFI-PC but there is no change.
Does anyone have an idea why the network connection works on legacy BIOS-PC and VM but not on UEFI PC?

**Comment by VanFlusen** [comment]
PhoenixPE 2023-01-30 and WIN10 19041.264

![10 0 19041](https://user-images.githubusercontent.com/82698833/216644730-53fb48be-d8ab-493c-be91-75c13edb5080.png)

PhoenixPE 2023-01-30 and WIN11 22621.382 
with the same settings.
PhoenixPE previously extracted again.

![10 0 22621 382](https://user-images.githubusercontent.com/82698833/216645574-9152980a-ecf5-4b63-87f3-373e9ca8b8ad.png)

Windows was able to install the missing driver (update driver).

![10 0 22621 382x](https://user-images.githubusercontent.com/82698833/216646459-96e14b32-143e-4748-a262-d5cb8387dbda.png)

Does nobody have this problem?
I did the builds with Intel UEFI-PC and AMD UEFI-PC.
I have no idea where the error is.

**Comment by homes32** [comment]
Do you have the PhoenixPE > Drivers > Network Drivers script enabled or disabled? The default is disabled. If you are able can you please test with the script enabled and see if the driver is included? If so it may be a build difference. I will attempt to find a few more PC's on my end to test and see if I can reproduce.

**Comment by VanFlusen** [comment]
Thanks for your reply.
I enabled and disabled the network driver script, there is no difference.
Always works fine on legacy PC.
It's strange, I don't own any exotic PC's.

**Comment by VanFlusen** [comment]
Would it be possible to download a PhoenixPE that you have created so that I can test if I have a build error?

**Comment by VanFlusen** [comment]
My two UEFI PC's have Intel network adapters and the PhoenixPE I built has no network driver on these PC's.

I was able to test today on a UEFI laptop with Realtek network adapter and Broadcom Wifi adapter and the PhoenixPE works fine.
I hope not that it's Intel's fault, I'll keep testing.

**Comment by VanFlusen** [comment]
I tested with a USB 3.0 LAN adapter (Realtek chip) and the network connection is available.
I integrated the drivers for "Intel(R) I211 Gigabit Network Connection" and "Intel(R) Ethernet Connection (5) I219-V" into PhoenixPE.
Alternatively, I added DrvIndex to install missing drivers from the host system at boot time.

**Comment by homes32** [comment]
Interesting. Thanks for posting your findings!

**Comment by VanFlusen** [comment]
The problem with the missing network drivers still exists when I use Win11 as the source.

No driver is installed for Intel Ethernet Connection I219-V and Intel I211 Gigabit Network Connection.

I was able to solve the problem by adding two entries to the NetworkDrivers.script:

![01](https://github.com/PhoenixPE/PhoenixPE/assets/82698833/80e6580f-8bfa-4418-b473-41b6f1cceaa5)

![02](https://github.com/PhoenixPE/PhoenixPE/assets/82698833/7c0b0555-743d-4eea-abf0-9e3ab528a1ec)

Is this possibly the reason why the driver was not installed?

https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/inbox-network-drivers?view=windows-11#Ethernet%20driver%20FODs

**Comment by homes32** [comment]
I think so. There are a couple more missing as well, so I'll get them added to the script.
