### ISSUE TITLE
[solved] plugin: RDP/RemoteDesktop v 1.0.0.0 from 2020-06-12 -  Error: 0x8007007e

### ISSUE THREAD

**Issue by ds2k5** [PhoenixPE/PhoenixPE#24]
Source: Windows 11 22H2

Plugin: projects\PhoenixPE\Components\RDP.script

When run mstsc.exe / RemoteDesktop an try to connect to a System got error: 0x8007007e
It do not matter Win10 / Win Server 2016 / Win Server 2022 always the same error.

How can I fix this ?

**Comment by homes32** [comment]
Hello,

This most likely has to do with Network Level Authentication (NLA) being the client default now, and your RDP session host not accepting NLA connections.

You can test by editing _X:\Users\Default\Documents\Default.rdp_ and adding `enablecredsspsupport:i:0` to the end of the file.

I did notice with the current RDP script does not properly handle situations where NLA config is not already present in the _Default.rdp_ file, so I will fix this in the next release. That will ensure that NLA always reflects the _Enable network level authentication_ checkbox on the script interface.

**Comment by ds2k5** [comment]
Thanks that worked for me

```

// Patch CredDialogController
If,%cb_PatchCredDialogController%,Equal,True,Run,%ScriptFile%,PatchCredDialogController

// Enable/Disable NLA
If,%cb_EnableNLA%,Equal,True,Begin
  TXTReplace,"%TargetDir%\Users\Default\Documents\Default.rdp","enablecredsspsupport:i:0","enablecredsspsupport:i:0"
End
Else,Begin
  TXTReplace,"%TargetDir%\Users\Default\Documents\Default.rdp","enablecredsspsupport:i:1","enablecredsspsupport:i:0"
End
```
