### ISSUE TITLE
total commander

### ISSUE THREAD

**Issue by adacom72** [PhoenixPE/PhoenixPE#25]
﻿

Checklist
---------
- [x ] I performed a search in the issue tracker to see if my suggestion has already been asked/answered by somebody else.

**Describe the solution you'd like**
A clear and concise description of what you would like to see implemented.

A request for Total commander script to be added to applications

**Describe why you believe your suggestion would benefit the project and members of the community at large**

just a good program that would add to the project
 
**Describe alternatives you've considered**

have tried existing scrips and non seem to work

**Additional context**

**Comment by homes32** [comment]
I agree. Though it is shareware, it has been in almost every PE project I can remember all the way back to UBCD4Win.
