### ISSUE TITLE
TODO: Shortcuts.exe needs to support all AddShortcut parameters. This requires rewriting a portion of shortcuts.exe

### ISSUE THREAD

**Issue by Rolf185** [PhoenixPE/PhoenixPE#34]
﻿

Checklist
---------
- [x] I performed a search in the issue tracker to see if my suggestion has already been asked/answered by somebody else.

I found this comment in PhoenixAPI.script. May be I can help with this. I'm using my own AutoIt script Shortcuts.au3 (of course a compiled version) to create shortcuts. The script creates full featured shortcuts on the fly during the build process even if the target file doesn't exist. But there's also an option to process the shortcut section in PECMD.ini at the end of a build or during PE startup.
Don't be confused if you look into. The script got more functions over the time and got more complex.
Look for "Func CreateShortcut" which does the work and for "Func PatchShortcut" which patches the shortcut file if the target doesn't exist.

Example to use it in a script:
// Shortcut "Directory|Filename[.lnk]|Target[|Parameter[|WorkDirectory[|IconFile[|IconIndex[|WindowState[|Hotkey[|Description]]]]]]]" ["/log[+][:LogFile]"
ShellExecute,hide,%Tools%\Toolbox\Shortcut.exe,#$q%_type%|%_filename%|%_target%|%_parameters%|%_workdir%|%_iconfile%|%_iconindex%|%_windowstate%|%_hotkey%|%_tooltip%#$q #$q%ProjectTemp%\Toolbox\Shortcut.script#$q %_log%
If,%ExitCode%,Equal,10,Echo,"%ScriptTitle%: Shortcut.exe %_type%|%_filename%|%_target%... ended: 10 - undefined.",Warn
If,ExistFile,%ProjectTemp%\Toolbox\Shortcut.script,Run,%ProjectTemp%\Toolbox\Shortcut.script,Messages

I'm happy if I can help this way. Even with some adaptation for PhoenixPE.
Rolf
[Shortcut.au3.txt](https://github.com/PhoenixPE/PhoenixPE/files/11010508/Shortcut.au3.txt)
[Shortcut.exe.txt](https://github.com/PhoenixPE/PhoenixPE/files/11010519/Shortcut.exe.txt)

**Comment by homes32** [comment]
Thanks for sharing!

That code is left over from some early prototyping of the AddShortcut command. 

At some point I would like to remove the dependency on PECMD, and I've done some experimenting with attempt to replace PECMD/pecmd.ini with a pure autoit script. still a ways out from anything close to production ready, as there is alot to test and replicate and when time is limited its hard to justify messing with something that is currently working ok. Keeping up with M$ Win11 issues takes enough as it is :)

**Comment by Rolf185** [comment]
Ok, shortcut.exe is one step to get rid ofPECMD.
Wolud you give it a try if I send an appropriate update for PhoenixAPI.script? No need then to use PECMD to create shortcuts.
Rolf

**Comment by homes32** [comment]
Resolved in 1c17ec77c3b58693a3330a88d21a0db8a5b8e76f
