### ISSUE TITLE
 How to add a simple AutoRun.cmd (batch-script) command?.

### ISSUE THREAD

**Issue by ElektroStudios** [PhoenixPE/PhoenixPE#37]
﻿

Checklist
---------
- [x] I performed a search in the issue tracker to see if my suggestion has already been asked/answered by somebody else.

It is possible to add a custom (batch-script) command to run a program (with parameters) located in the desktop after the shell is loaded?.

Example:
AutoRun.cmd
`@Echo OFF`
`Start /W "" "%UserProfile%\Desktop\MyProgram.exe" /parameters`
`Exit`

This was very easy to do with WinBuilder, but I can't find a equivalent feature in PEBakery / ProhenixPE project plugins.

I seen the "TweakBox" feature which contains this example line:

`//AddAutoRun,PreShell,HideNoWait,"Loading additional drivers...","pnputil.exe","/add-driver Y:\Drivers\*.inf /subdirs /install"`

I'm not sure If this feature can be used as an equivalent for what I need, and in that case how can I adapt that example line to run a executable file (or a .cmd file) after shell, like something like this:

` AddAutoRun,PostShell,Normal,"Running MyProgram...","Y:\Users\Default\Desktop\MyProgram.exe","/parameter"`

Is there any documentation to learn the syntax of this?.

I found this, but the syntax differs a lot:
 - https://documentation.help/WinBuilder/addautorun.html

**Comment by ElektroStudios** [comment]
I was able to run a cmd script file with this:

`AddAutoRun,PostShell,HideNoWait,"Running AutoRun.cmd ...","Y:\Programs\AutoRun.cmd",""`

The "PostShell" was just deductive, pure luck. However, I didn't had the same deduction luck when changing the paramater "HideNoWait" to "Normal". 

How can I specify to make the window visible?. Because it does not only hides the CMD window, it also hides any child process ran within the hidden CMD instance.

**Comment by homes32** [comment]
The [PhoenixPE Wiki](https://github.com/PhoenixPE/PhoenixPE/wiki) is your best friend for answering these questions.

Check out the sections titled:
[PhoenixAPI Commands](https://github.com/PhoenixPE/PhoenixPE/wiki/PhoenixAPI)
[Project Variables](https://github.com/PhoenixPE/PhoenixPE/wiki/ProjectVars)

**Comment by ElektroStudios** [comment]
Thanks a lot!.
