### ISSUE TITLE
HWiNFO script is unable to download HWiNFO.

### ISSUE THREAD

**Issue by ElektroStudios** [PhoenixPE/PhoenixPE#39]
﻿

Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
Issue urgency: low

The PHoenixPE build stops abruptly in the HWiNFO script due it seems unable to request a working download url:

`[Warning] WebGet - An error occurred while downloading [https://www.hwinfo.com/files/hwi_740.zip] (WebGet,%DownloadURL%,"%ProgramsCache%\%ProgramFolder%\%SetupFile%",Referer=https://www.hwinfo.com/download/,NOERR) (Line 117)`

I tried this updated download url in my web-browser and it is not working: https://www.hwinfo.com/files/hwi_742.zip - it just redirects me to https://www.hwinfo.com/download/ ...

So I think the unexpected url redirection could be the main problem that breaks the PhoenixPE build procedure.

I'm not sure whether a script can have contained html parsing logic, but if helpful this url will show the download links for the latest release: https://www.fosshub.com/HWiNFO.html - so in case of it can be parsed then it will always list the latest release.

But, in short, and as for now, this is the right download url: https://www.fosshub.com/HWiNFO.html?dwl=hwi_742.zip

**Comment by homes32** [comment]
bumping the ProgramVersion on line 45 to `%ProgramVersion%=742` will correct this. HWInfo has started moving old releases to another server when they update, which breaks the download.

**Comment by ElektroStudios** [comment]
You make it look so easy haha. I focus on what the problem causes me, without messing with the script source-code. 

Thanks for the support.
