### ISSUE TITLE
Write Protect RM program should not allow multi-instance.

### ISSUE THREAD

**Issue by ElektroStudios** [PhoenixPE/PhoenixPE#40]
﻿

Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
Issue urgency: low

I'm writing here this report because I checked in the version info of the 'Write Protect RM' executable file, that the copyright is of @[Homes32](https://github.com/homes32). Although I don't know whether 'Write Protect RM' has its own GitHub repo to make there this report... 

The thing is that 'Write Protect RM' should be designed as a single-instance program, that is, to don't allow running multiple instances of this program as this program does not have any benefit from multi-instancing it....

![](https://i.imgur.com/Uib2aSW.png)

That's all. Thanks for your time!

**Comment by homes32** [comment]
Agreed. fixed in [141eeb8](https://github.com/PhoenixPE/PhoenixPE/commit/141eeb8f751fb5932598aae556bf5ab90db1a7f3)
