### ISSUE TITLE
Microsoft WordPad is not working in WinPE environment.

### ISSUE THREAD

**Issue by ElektroStudios** [PhoenixPE/PhoenixPE#42]
﻿

Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
﻿Issue urgency: medium

Win10 source: Windows 10 2004 (10.0.19041.264) EN
PhoenixPE project settings: minimal, almost default. But I also tested it with a more complex project with loads of scripts enabled.

Problem description:
I just noticed that MS Wordpad is not working in the WinPE environment. It is unable to start.

I suppose some kind of missing file dependency could be the problem. Anyways, I tried to figure out what is happening with the help of Event Viewer, but then I discovered an additional issue that stops me from using Event Viewer: https://github.com/PhoenixPE/PhoenixPE/issues/41

So... this is what I can give you this helps: 

SysInternals Process Monitor activity log for Wordpad: https://www.mediafire.com/file/rm38lm23ol0t4iq/Wordpad+Logfile+Process+Monitor.zip/file

( With Process Monitor I can't figure out the problem, or at least I didn't found anything interesting. Maybe the log is useless, but who knows, I'm not an expert on debugging external things like this. )

**Comment by homes32** [comment]
Something appears to be wrong with SxS in the 2004 build. 1909 and Win11 are working as expected.

**Comment by ElektroStudios** [comment]
> Something appears to be wrong with SxS in the 2004 build. 1909 and Win11 are working as expected.

Excuse me but this will mean that it has not or can't figure a fix for the specific Windows 10 2004 build version?.

I will describe the steps for a temporary workaround:

1. Download this: https://www.askvg.com/how-to-get-the-good-old-wordpad-without-ribbons-working-in-windows-7/
2. Replace that wordpad.exe for the original one that is in the directory "..\Program Files\Windows NT\Accesories"
    Also include in that directory the the mfc42u.dll file. (if running a 64-Bit OS copy the mfc42u.dll from syswow64 directory, not from system32).

**Comment by ElektroStudios** [comment]
I found that same problem occurs with ms paint.

**Comment by homes32** [comment]
Issue was caused by a gdiplus.dll SideBySide version mismatch between WinRE SOFTWARE hive and Install.wim SOFTWARE hives and the component store.
