### ISSUE TITLE
Powershell

### ISSUE THREAD

**Issue by tsherrington** [PhoenixPE/PhoenixPE#48]
It would be useful if Powershell was available inside the built PE.  It would extend the usefulness of the project, since there's a lot that can be done in PowerShell that can't be done in batch scripting.

﻿There are some Powershell script addons for Win10PESE:
http://win10se.cwcodes.net/Projects/Win10PESE/Components/MsPowerShell_Core.Script
http://win10se.cwcodes.net/Projects/Win10PESE/Components/MsPowerShell.script

I'm not sure if these can be added to PhoenixPE.

Thanks!

**Comment by homes32** [comment]
Did you check the included apps? We've had Powershell for quite some time ;)

![2023-05-16_20-47-57](https://github.com/PhoenixPE/PhoenixPE/assets/6519152/6289985c-fb44-4e41-b559-052469c5777f)

**Comment by tsherrington** [comment]
Dear Lord, but I'm an idiot. :)  Thank you for pointing this out.  Sorry to have taken up time and space on this.

**Comment by homes32** [comment]
no worries!
