### ISSUE TITLE
script errror

### ISSUE THREAD

**Issue by aychupkar** [PhoenixPE/PhoenixPE#5]
sumatrapdf & Attribute Changer script give error
download url is not working
please modifyboth and reload both.
Thanks

**Comment by homes32** [comment]
Sumatra script was updated for v3.4.6
 https://github.com/PhoenixPE/PhoenixPE/blob/master/Projects/PhoenixPE/Applications/Productivity/SumatraPDF.script

I'm not able to reproduce your issue with Attribute Changer. The installer downloads fine and the MD5 hash matches the hash posted on the official download page.
