### ISSUE TITLE
Stuck on Removing old support logs... for over an hour

### ISSUE THREAD

**Issue by RDKRACZ** [PhoenixPE/PhoenixPE#51]
﻿

Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
﻿

**Describe what is happening**
Step 29/29 - Create ISO. Script Progress 67,2%, Full Progress 98,9%. It's been like that for 1h. No errors.

**To Reproduce**
Step-by-step instructions on how to reproduce the behavior:
No idea

**Screenshots/Logs**
If applicable provide any error messages, log files, screenshots, scripts, etc. that may be helpful for troubleshooting or further explain your issue.
![obraz](https://github.com/PhoenixPE/PhoenixPE/assets/43277609/3f11af07-118e-4a96-b2dc-4f6510c3c0ae)

**Comment by homes32** [comment]
I haven't been able to reproduce this, nor has there been any other reports, and you did not provide a log file, so for now I'm going to assume it was something local with your path or environment.

the remove support logs function is a single powershell command
`ShellExecute,Hide,"powershell.exe","-ExecutionPolicy Bypass -Command #$q$files = Get-ChildItem -Path '%BaseDir%\Logs' -Recurse | Where-Object {-not $_.PsIsContainer}; if ($files.Count -gt %num_LogsToKeep%) { $files | Sort-Object CreationTime | Select-Object -First ($files.Count - %num_LogsToKeep%) | Remove-Item -Force }#$q"` clearly something is causing powershell to hang

The best troubleshooting advice I can give with this information is to check your log and try running the full command (ex. `powershell.exe -ExecutionPolicy Bypass -Command "$files = Get-ChildItem -Path 'P:\PhoenixPE\Logs' -Recurse | Where-Object {-not $_.PsIsContainer}; if ($files.Count -gt 10) { $files | Sort-Object CreationTime | Select-Object -First ($files.Count - 10) | Remove-Item -Force }"`) from a standalone elevated command prompt and see if you get any useful output/error messages.
