### ISSUE TITLE
Add Dism++

### ISSUE THREAD

**Issue by kevinwijnb** [PhoenixPE/PhoenixPE#54]
Checklist
---------
- [x] I performed a search in the issue tracker to see if my suggestion has already been asked/answered by somebody else.

**Describe the solution you'd like**
Please add Dism++ because I can't live without this tool in my PE 😊

**Describe why you believe your suggestion would benefit the project and members of the community at large**
 I would like everyone to benefit from this amazing program. It saved my Windows installations errors multiple times.

**Describe alternatives you've considered**
None

**Additional context**
https://github.com/Chuyu-Team/Dism-Multi-language

**Comment by schrebra** [comment]
I needed to convert an install.esd to install.wim and I looked under the tools section and I was thinking the same thing. I ended up using dism ++

**Comment by josephworks** [comment]
I actually ended up making this last night! Here's my script:
https://gist.github.com/josephworks/f25f06da42656ebf78c079bc641e2b3a

**Comment by homes32** [comment]
I'm curious what most people use this for? Most of the tasks can be performed just as easy with DISM itself, while other features are not useful inside WinPE (aka need an Online system).

Alot of people I have talked to are turned off by the bizarre license agreement that requires you to write an essay to the author every year reporting on your usage, gives them the rights to collect your system crash dumps and logs (which can contain very sensitive information) ,and subjecting you to Chinese law if you do not comply with the terms of the license. That and the fact that the author has stated he is no longer actively developing this tool and it hasn't been updated in the past 5-6 years is another concern as it has the potential of being broken by M$ at any given time for newer windows versions. Those are the 2 main reasons it's not included in PhoenixPE at this time.

I'm open to hearing your arguments for or against inclusion though.

**Comment by kevinwijnb** [comment]
Never read the license and the usage terms myself (oops).

I use this tool for adding drivers to a Windows OS mostly, after cloning it from another drive.

**Comment by schrebra** [comment]
I've never read the license either. Dism is cmd line. Dism ++ is click a few buttons to convert an esd to a wim.

**Comment by josephworks** [comment]
Dism++ comes with a Disk Cleanup utility, Driver utility, Windows Update utility, Account Management, Startup Repair, and many other utilities. It is one of the most popular softwares that I use as an IT Adminstrator.

Here are some screenshots I got from MajorGeeks:
![image](https://github.com/PhoenixPE/PhoenixPE/assets/18745823/cbdc28f3-e978-49ae-8b86-f74883603132)
![image](https://github.com/PhoenixPE/PhoenixPE/assets/18745823/770de4d0-d9f2-4d92-a734-473556bf6eb3)

**Comment by josephworks** [comment]
> Most of the tasks can be performed just as easy with DISM itself, while other features are not useful inside WinPE (aka need an Online system).

When running under PE, Dism++ will locate offline windows installations and you can simply click and it will switch over to it.

Installations are usually to the right of the blue box with the system info.

![image](https://github.com/PhoenixPE/PhoenixPE/assets/18745823/f948c209-4ac4-4bc1-8008-193e0a692028)

**Comment by josephworks** [comment]
@homes32 Thank you! Please feel free to close the issue and get it off your plate.
