### ISSUE TITLE
Show expected size at components and applications

### ISSUE THREAD

**Issue by kevinwijnb** [PhoenixPE/PhoenixPE#57]
Checklist
---------
- [X] I performed a search in the issue tracker to see if my suggestion has already been asked/answered by somebody else.

**Describe why you believe your suggestion would benefit the project and members of the community at large**
It would help to have an idea of how big the result image gets increased with each option.
This is especially helpful for images which are being used for PXE servers.
 
**Describe alternatives you've considered**
Show expected file size for each component and application.

**Additional context**
None

**Comment by homes32** [comment]
If you click on the info icon on each app script most will tell you the download size and you can get a decent idea of what each script costs in terms of size increase.

Unfortunately that is as close as you are likley to get. There are just too many variables for something like this to be accurate, even if it was possible to run calculations on the fly (https://github.com/pebakery/pebakery/issues/157), someone would still have to manually mantain a estimated size variable that would likley be wrong 50% or more of the time. Download size does not always match extracted size, and alot of app scripts are dynamically downloaded,  so we have no idea what changes from release to release until its unpacked. Some scripts also have different options that can add/remove components. Language/international preferences have an impact, as does a localized ISO file. Too much guesswork and maintenance for not enough gain.
