### ISSUE TITLE
 System Sound Patch with latest Windows 11

### ISSUE THREAD

**Issue by ChrisRfr** [PhoenixPE/PhoenixPE#58]
Hello Jonathan,
Just to let you know.
The Windows 11 System Sound Patch works with AudioSrvPolicyManager.dll v10.0.22621.1 but not with the latest version of this dll v10.0.22621.1485.
So, with latest Windows11 v10.0.22621.1702 ISO, the sound does not work with the System account, it requires Admin account login, sessions.

**Comment by homes32** [comment]
Thanks for the heads up Chris!

**Comment by homes32** [comment]
Patching has been updated to work with Win11 22621.1702

Please download the [latest copy](https://raw.githubusercontent.com/PhoenixPE/PhoenixPE/master/Projects/PhoenixPE/Components/320-Audio.script) of the Audio script.

**Comment by ChrisRfr** [comment]
Thanks, I confirm that it works with Win11 22621.1702 :smile:

If,Not,#r,Equal,0,Echo,"ERROR:..." does not seem necessary, the return code is always 0.  
If the string is not found, the return code is 0, Done: 0 matches.

**Comment by homes32** [comment]
> If,Not,#r,Equal,0,Echo,"ERROR:..." does not seem necessary, the return code is always 0. If the string is not found, the return code is 0, Done: 0 matches.

That is true at present, But I am in the habit of always checking the exit code of any tools as a best practice. This way if in the future a program changes it's behavior or I make a mistake building the command then I already have a method in place to catch it during testing (Warning/Error in build log) and troubleshoot the issue. 

There is room for a little cleanup though. I noticed I was not using the verbose flag and can save some code...

Thanks for verifying!
