### ISSUE TITLE
OCCT License File

### ISSUE THREAD

**Issue by catherinedoyel** [PhoenixPE/PhoenixPE#60]
﻿

Checklist
---------
- [x] I performed a search in the issue tracker to see if my suggestion has already been asked/answered by somebody else.

The license file `license.okl` which is needed for more than 1hr run time needs to be in the same folder as `OCCT.exe`. 
If I was not using run all programs from RAM I know how to put in the same folder, but I am running from netboot.
 
**Describe alternatives you've considered**
I am not familiar with WinBuilder/PEBakery scripting, but perhaps modify the Post-Process script to copy the file into the correct path? 

**Additional context**
I looked at the AutoBackup7Pro listing and I can see that it's possible to add a license key, but I can't understand how it's done.

**Comment by homes32** [comment]
Hi,

If you have the license.okl file the quick & dirty way to get up and running if you have already built the project is to simply copy the file to `<PhoenixPEdir>\Workbench\PhoenixPE\Target\Program Files\OCCT` then press the `Rebuild WIM Image` button on the Vmware script to repack the .wim

I don't have any objections to adding a filebox to the OCCT script so you can copy the license file and/or config.json into the build automatically if you are willing to test it. I don't currently have a license file myself for testing.

see the Notepadd++ script (press the gear in the upper right to show advanced options) for an example of how this method would work.

**Comment by homes32** [comment]
Please test [this updated script ](https://raw.githubusercontent.com/PhoenixPE/PhoenixPE/6e73ecee0160a801cc44d85acf68634f8c0cc93e/Projects/PhoenixPE/Applications/Benchmarking/OCCT.script) and see if it meets your needs.

In addition, if your interested in PEBakery's scripting language, there is extensive documentation available [here.](https://github.com/pebakery/pebakery-docs)

**Comment by catherinedoyel** [comment]
Thank you very much! I see how the scripting for the gui works now, starting to understand the backend.
