### ISSUE TITLE
AddShortcut: Shortcut creation will fail if comma-separated string as parameter is given

### ISSUE THREAD

**Issue by Mikka-TheOne** [PhoenixPE/PhoenixPE#62]
﻿
Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
﻿**AddShortcut: Shortcut creation will fail if comma-separated string as parameter is given**

I tried to add the following shortcut for explorer.exe:
`%windir%\explorer.exe /e,/subobject,%SystemDrive%
`

With this parameter, explorer.exe displays the content of X: at startup.

AddShortcut will give me this: _%windir%\explorer.exe /e_ - i.e. a shortened/invalid shortcut, the comma acts as delimiter.
It makes no difference if commas are replaced by `#$c`.

**Reproduction**
1. `AddShortcut,Desktop,,"File Explorer","#$pwindir#$p\explorer.exe","/e,/subobject,#$pSystemDrive#$p"`
2. Do a build using this line.

**Comment by homes32** [comment]
Resolved in 1c17ec77c3b58693a3330a88d21a0db8a5b8e76f
