### ISSUE TITLE
Script highlighting "WinBuilder Classic" style for Notepad++

### ISSUE THREAD

**Issue by Mikka-TheOne** [PhoenixPE/PhoenixPE#63]
﻿Checklist
---------
- [x] I performed a search in the issue tracker to see if my suggestion has already been asked/answered by somebody else.

**Improve editing scripts with Notepad++**
[Notepad++](https://notepad-plus-plus.org/) as external editor for PEBakery lacks built-in syntax highlighting for `.script` files.
Thanks to its [UDL](http://ivan-radic.github.io/udl-documentation/) feature, this can be added.

I tried to mimic WinBuilder's highlighting of the _Win8.1SE project_ to which I've gotten used to over the years.
I've made adjustments for PhoenixPE, for instance in terms of commenting and new commands.

![Scriptscr](https://github.com/PhoenixPE/PhoenixPE/assets/152649471/01b4f47d-22cb-4fb8-97ad-af2356239933)
(Using the editor's default font it should look exactly like it did in WinBuilder back then.)

The highlighting file can be easily adopted. However, I'm still looking for a scripting option to automate this.
This way it could also be used for a PE build.

[UDL_WinBuilderClassic.zip](https://github.com/PhoenixPE/PhoenixPE/files/13532379/UDL_WinBuilderClassic.zip)

**Comment by homes32** [comment]
You can grab the full PEBakery UDL here; https://github.com/pebakery/npp-udl-pebakery

**Comment by Mikka-TheOne** [comment]
Nice, however, I'll stick with my WinBuilder Classic with additional comment folding.
Everything beyond this, such as AutoComplete/Hints, is limited to an IDE.
