### ISSUE TITLE
Split 310-Networking.script in two: one for network functionality and one for PENetwork

### ISSUE THREAD

**Issue by Mikka-TheOne** [PhoenixPE/PhoenixPE#64]
In **Win10PESE**, [network functionality](http://win10se.cwcodes.net/Projects/Win10PESE/Components/Network.script) and [PENetwork settings](http://w7pese.cwcodes.net/Projects/Win7PESE/Components/penetwork.script) are separated from each other, unlike in PhoenixPE (merely _PhoenixPE\Components\310-Networking.script_).

The one script approach poses several difficulties:

- Its UI is prone to misunderstandings, unlike the [PENetwork-only script](http://w7pese.cwcodes.net/Projects/Win7PESE/Components/penetwork.script).
- A user customised `PENetwork.ini` in _%ProgramsCache%\PENetwork_ isn't permanent (→ NukeProject).
- PENetwork settings being handled by the script might overwrite a pre-customised `PENetwork.ini`.
- Keeping all customised data in, e.g. _%Workbench%\PENetwork_, isn't feasible.

The PENetwork-only script provides an option to add missing network drivers, too.

It would be good having two scripts instead of one.

**Comment by homes32** [comment]
Thank you for the feedback.

I'm not opposed to separating PENetwork from the regular networking components and actually have considered doing so for various reasons, so I will revisit this thought.

>Its UI is prone to misunderstandings, unlike the [PENetwork-only script](http://w7pese.cwcodes.net/Projects/Win7PESE/Components/penetwork.script).

I have no intention of duplicating PENetworks config on the script interface. One really nice thing PENetwork has going for it is a full featured multi-profile config editor. Adding redundant config just complicates the scripting and could lead to inadvertently overriding custom config files among other issues. The average user doesn't need to be presented with that many options, and those who do generally can be expected to know what they want in the profile editor and probably have a custom config file anyway.

>A user customised PENetwork.ini in %ProgramsCache%\PENetwork isn't permanent (→ NukeProject).

>Keeping all customised data in, e.g. %Workbench%\PENetwork, isn't feasible.

Agreed. This needs to be addressed in a future release.

>The PENetwork-only script provides an option to add missing network drivers, too.

This can be done via the Drivers > Driver Integration script. I prefer not to duplicate functionality if it can be helped. Previous projects sometimes made things more confusing by having 3-10 different ways to do the same thing spread across scripts.

_Did I included that file in Copy Files, Additional Files, Drivers, or was it PENetwork?_

Regards,
Homes32

**Comment by Mikka-TheOne** [comment]
The attached version isn't an improvement of the current stable one, but an adapted version to speed up my building process.
I've commented on relevant script changes (search for "Mikka" or "makeshift"). In case you are interested.

[310-Networking_modified.zip](https://github.com/PhoenixPE/PhoenixPE/files/13661279/310-Networking_modified.zip)

**Comment by homes32** [comment]
> The `netsh` command expects the actual **wlan name**, not the name of the credentials' file _(%WifiConfig_FileNameNoExt%)_. I inserted the corresponding SSID name into the script instead and it worked.

Correct. in this case the script is assuming that you left the name as the SSID, as is the default of the export tool. Of course this is not ideal and needs to be handled better. I actually have not come across anyone who uses this "feature" yet, most just add it directly in the PENetwork editor and/or use a custom config. Which brings us to 

> A command to read out a XML file seems to be lacking in PhoenixPE. With [XMLStarlet](https://xmlstar.sourceforge.net/), I'd do something like: `xml sel -t -v "//_:SSIDConfig/_:SSID/_:name/text()" %WifiConfig_FileName%`

Also true, I never got around to adding XML read to the PhoenixAPI as contriving a "generic" command was proving more complicated to handle the complexity of XML (attributes, nodes, and namespaces) via PEBakery script and an external exe. Around the time Joveler was also indicating that he planned to [add XML/JSON support directly](https://github.com/pebakery/pebakery/issues/140) to PEBakery, which is still in the works.

I'll take a look at your modifications and see what can be further improved. Thanks for taking the time to provide all the feedback!
