### ISSUE TITLE
Script organisation improvements like Depend=, Disable= from former WinBuilder

### ISSUE THREAD

**Issue by Mikka-TheOne** [PhoenixPE/PhoenixPE#65]
I keep my scripts in `Projects\MyApps\...` and came across a problem:

1. Let's assume I've got a _310-Networking.script_ both in `Projects\PhoenixPE\Components` and in `Projects\MyApps\Components`, the latter being a customised/revised version. As long as my script is selected, I like the other one to be disabled (Selected=False) and vice versa. In WinBuilder it was feasible to include a line `Disable=<path-to-the-script>` in the `[Main]` section to provoke that behaviour (it was a bit quirky, however).

2. Another use case is dependent scripts. Back then there was a feature `Depend=<path-to-another-requirement-script>` to ensure required scripts were integrated (i.e. selected) automatically. I remember that the Mozilla Firefox script benefited from this feature.

Both options seem to be missing in PEBakery. It could be worth considering for an upcoming release.

**Comment by homes32** [comment]
The Winbuilder implementation was terrible, which is why it was almost never used and was not ported to PEBakery. I remember many threads of complaining on the old reboot forum how unreliable and quirky it was.

It would be nice to have, there are a few instances where I would definitely use the functionality in PhoenixPE. Shell scripts such as openshell/startallback, etc.

I would not want it to mirror Winbuilders behavior though. It would make more send to base it off of a GUID then a script name/path.

**Comment by homes32** [comment]
> Would it be technically possible to prioritise `Projects\MyApps` over `Projects\PhoenixPE` and, if present, execute all scripts there being marked as selected? This would solve point 1, even without a `Disable=` entry.

There are a couple options, neither of them perfect or suitable for all use cases, but might be good to be aware of.

1. You can make use of the [AddPostProcess](https://github.com/PhoenixPE/PhoenixPE/wiki/AddPostProcess) command in the PhoenixAPI to run specific code **at the end** of the build process. In this way you don't need to have personal copies of all the scripts where you want to make small changes, as long as the changes are acceptable to make at the end of the build. Ex. Copy your personal PENewtork.ini to %TargetPrograms%, make some registry changes, etc.
2. You can modify the [Script Level](https://github.com/pebakery/pebakery-docs/blob/develop/Projects/ScriptLevels.md) in your scripts to run in a later stage in the build process. See [PhoenixPE build levels](https://github.com/PhoenixPE/PhoenixPE/blob/master/Projects/MyApps/README.txt). This ensures your script is executed after the project scripts, though does not prevent duplicate actions like autoruns, shortcuts, etc from being created if the original script still runs, so I don't recommend this approach.
3. Create a script/button that you could run once when the project is updated that would disable the project scripts you don't want. Ex. `IniWrite,"051-StartIsBack++.script","Main","Selected","None"` or `IniWrite,"051-StartIsBack++.script","Main","Level",-3`. Note that this would be a manual process to execute when you updated. You can't do this "in build" as once the build is running the scripts are cached in memory and updates to the .script file on disk will not be recognized until next build.

**Comment by Mikka-TheOne** [comment]
Thanks for the listing, I haven't yet got a use case for no. 1, although I've been experimenting with it for a tough registry setting that I just can't get to work so far. (In the WinBuilder past there was the `RegAddBoot` command for similar tasks.)

No. 3 looks promising and is a good compromise, especially for non-trivial changes. I'll try that.

**Comment by homes32** [comment]
> (In the WinBuilder past there was the `RegAddBoot` command for similar tasks.)

The closest thing to `RegAddBoot` is a new command I introduced in the master branch to solve some use cases that came about with the move from PECMD to Autoit script handling the startup tasks.

[AddStartupConfig](https://github.com/PhoenixPE/PhoenixPE/wiki/AddStartupConfig) will let you add pure [autoit code](http://www.autoitscript.com/autoit3/docs/) to the startup config so you can use this to modify the registry during starting like RegAddBoot did, but with a little more control over when it happens.

```
AddStartupConfig,PostConfig,"RegWrite(#$qHKLM\SYSTEM\SomeKey#$q, #$qSomeValue#$q, #$qREG_DWORD#$q, 0)"
```

keep in mind this hasn't been bundled up into a release as there are still some issues to work out with the latest Win11 23H2v2 ISO, but if your comfortable you can update from github and give it a try.
