### ISSUE TITLE
Can WinPE Cache Size be changed after building?

### ISSUE THREAD

**Issue by VanFlusen** [PhoenixPE/PhoenixPE#66]
I built PhoenixPE and customized it a lot.
The standard size is sometimes not enough or borderline.
So I would like to expand the size to 4094 MB if possible without rebuilding.
Is this possible?

**Comment by VanFlusen** [comment]
I have changed the value under:
"HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\FBWF\WinPECacheThreshold"
to 4096 MB and it works.
Is there a reason why a value of **4094** MB can be selected in PEBakery?

**Comment by homes32** [comment]
> Is there a reason why a value of **4094** MB can be selected in PEBakery?

4094 (just under 4 GB) is the max value that you can set the WinPE Cache with Win10. If you try and set it to set anything higher, such as 4096, Windows will just reset it to 512 MB cache when you boot WinPE.

If you are building with a Win11 source this limit seems to have been removed or at the very least modified. I tested at least 16 GB on Win11 22H2, so I'll do some more testing and allow larger WinPE Cache selection in a future release.
