### ISSUE TITLE
The selection of available languages in "Attribute Changer" is swapped

### ISSUE THREAD

**Issue by VanFlusen** [PhoenixPE/PhoenixPE#67]
Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
﻿PEBakery -> Applications -> System Tools -> Attribute Changer:

The available languages are swapped.
If I select German, I get Italian after building.

![01](https://github.com/PhoenixPE/PhoenixPE/assets/82698833/82e348f6-dc66-4d47-b889-3812b23bb0e5)

![02](https://github.com/PhoenixPE/PhoenixPE/assets/82698833/37197a12-d1d2-47d6-967e-6e0f33503caa)

C:\PhoenixPE\Output\PhoenixPE_de-DE_x64.iso\Programs\Attribute Changer\

![03](https://github.com/PhoenixPE/PhoenixPE/assets/82698833/504dab76-e2ac-4c3e-811d-23b6a00eaeea)

To remedy this for me, I inserted the files of the new version of Attribute Changer Portable (v11.30) with messages.ini (German message file) into the ISO and recreated them.

**Comment by Mikka-TheOne** [comment]
I upgraded that script and fixed the problem, find my version attached.

It might also occur that the PEBakery process stops due to a failure - namely the download process from [petges.lu](https://www.petges.lu/).
That has happened to me twice so far.

[AttributeChanger.zip](https://github.com/PhoenixPE/PhoenixPE/files/13835585/AttributeChanger.zip)

**Comment by VanFlusen** [comment]
Thanks for your help.
I have tested it and it works fine.

**Comment by homes32** [comment]
Got it sorted out. Attrib Changer dropped support for Portuguese, Dutch, and Romanian and added Korean so it threw all the file numbers off in the installer.
