### ISSUE TITLE
DISMTool.script - updated version available

### ISSUE THREAD

**Issue by PCAssistSoftware** [PhoenixPE/PhoenixPE#69]
Hi

I am the author of DISM Tool which you include here = 

https://github.com/PhoenixPE/PhoenixPE/tree/master/Projects/PhoenixPE/Toolbox

Currently you are using v2.6 of my tool, just to let you know there is a newer improved version (v2.8) available that you can include if you wish :)

There are also other PE related tools on my website which may be useful - you already include Installed Software PE, but I also have Event Viewer PE and Disk Check PE - see here https://www.pcassistsoftware.co.uk/free.html

**Comment by homes32** [comment]
Thanks for the heads up Darren,

Once we work out why Win11 23H2v2 keeps crashing explorer I'll get everything up to date for another release. Thank you for making your work available and your contributions to the PE scene!
