### ISSUE TITLE
pecmd.ini - section (_sub) Init - keyword Init already pre-assigned - section never gets called

### ISSUE THREAD

**Issue by Whatslp** [PhoenixPE/PhoenixPE#70]
Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
pecmd.ini - subsection (_sub) Init - keyword Init is already pre-assigned - section never gets called
solution:
rename **Init** to **OSInit** and all references to it

**Comment by homes32** [comment]
Thanks. won't be in issue in the next release.
