### ISSUE TITLE
LetterSwap - code correction + some error handling

### ISSUE THREAD

**Issue by Whatslp** [PhoenixPE/PhoenixPE#71]
Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
LetterSwap.au3

I misspelled one parameter and it took me hours to figure out why the tool is not working. It did not give me any useful info.
So i did some code correction and added error handling regards the parameter and recompiled it as command line version.

I put everything in here (updated Version):
[LetterSwap.zip](https://github.com/PhoenixPE/PhoenixPE/files/14155209/LetterSwap.zip)

**Comment by homes32** [comment]
The error handling seems like a good idea. Too late to get in this release, but I'll look at adding the changes for the next.

**Comment by Whatslp** [comment]
Additional Error:
**LetterSwap - does not worked correct during startup in the early stages.**
**Reason:**
Function **_MountAll()** tries to access a registry key that is not availably during startup:
**HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\MountPoints2\CPC\Volume**
I replaced the function so it works without the need of this registry entry.
[LetterSwap.zip](https://github.com/PhoenixPE/PhoenixPE/files/14155209/LetterSwap.zip)

**Comment by homes32** [comment]
I've added your improvements to MountAll() along with pieces of your other improvements to the production version. 

I've also published the LetterSwap code to it's own repository since the original topic on The Oven was moved to a static archive. 
You can view the code here: https://github.com/PhoenixPE/LetterSwap/tree/master
