### ISSUE TITLE
AddShortcut - incorrect handling of parameters

### ISSUE THREAD

**Issue by Whatslp** [PhoenixPE/PhoenixPE#72]
Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
﻿AddShortcut - incorrect handling of parameters

test.script:
AddShortcut,Desktop,,"cmd1",%SystemRoot%\System32\cmd.exe,aaa,bbb,ccc,ddd
**pecmd.ini (here is the issue):**
LINK %Desktop%\cmd1,%SystemRoot%\System32\cmd.exe,aaa,**ccc#ddd**,,bbb
**should be:**
LINK %Desktop%\cmd1,%SystemRoot%\System32\cmd.exe,aaa,**ccc,ddd**,bbb
after startup:
// aaa - Parameter
// bbb - Start in
// ccc - Icon
// ddd - gets lost in the process
//
test.script:
AddShortcut,Desktop,,"cmd2",%SystemRoot%\System32\cmd.exe,aaa,bbb,ccc
pecmd.ini:
LINK %Desktop%\cmd2,%SystemRoot%\System32\cmd.exe,aaa,ccc,,bbb
after startup:
// aaa - Parameter
// bbb - Start in
// ccc - Icon
//
added directly into pecmd.ini:
LINK %Desktop%\cmd3,%SystemRoot%\System32\cmd.exe,Par1,Par2,Par3,Par4
// Par1 - Parameter
// Par2 - Icon
// Par3 - Comment
// Par4 - Start in

**Comment by homes32** [comment]
no longer an issue as shortcut creation has been completely re-written in the 2024-01-14 release.
