### ISSUE TITLE
Missing desktop.ini file

### ISSUE THREAD

**Issue by schrebra** [PhoenixPE/PhoenixPE#75]
﻿

Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
﻿

**Describe what is happening**
When booting up a freshly made PE.iso there is a missing file and asks if It can save a new one. The file is called desktop.ini . I have built 8 different versions of PE.isos with different settings and windows sources. Ive tried looking at the newly made PE.iso install.wim file and went to the directory where it said the file was missing and it shows the file as being there. I did thorough research to see if this issue was documented before with no luck.

I looked through the PheonixPE log file and the only thing relevant to this error are these lines below. Ill attach the full log in case I missed anything.

[PhoenixPE.log](https://github.com/PhoenixPE/PhoenixPE/files/13982313/PhoenixPE.log)
```
14:23:45:826 Loading the Shell...
14:23:45:826 The Shell is already running.
14:23:45:826 PostShell Processing...
14:23:45:826 RunProgram(): [X:\windows\system32\attrib.exe +s +h X:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup] PID 2420 started.
```
The missing file is desktop.ini

The location of the missing file is X:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup

Current source build is Windows 10 20H2

Seems like something is deleting that file after the fact.

**To Reproduce**
Step-by-step instructions on how to reproduce the behavior:
1. Boot into the WindowsPE.iso
2. Wait until it shows the error message below.

**Expected behavior**
When booting into the PE.iso I expect there to be no errors.

**Screenshots/Logs**
If applicable provide any error messages, log files, screenshots, scripts, etc. that may be helpful for troubleshooting or further explain your issue.

![image](https://github.com/PhoenixPE/PhoenixPE/assets/34587652/73fe9649-a5d5-4ef0-9c3a-4af288dcbd74)

![image](https://github.com/PhoenixPE/PhoenixPE/assets/34587652/ca6085b3-19d2-4afe-912c-a8f61bbe7556)

![image](https://github.com/PhoenixPE/PhoenixPE/assets/34587652/f88d912d-742f-48ba-995c-ac8560b15e61)

**Comment by homes32** [comment]
I'm able to reproduce this with a Win10 source and have an idea where the problem might be. Thanks for reporting.

**Comment by schrebra** [comment]
I wanted to give more information while I try out different configurations. I tried Windows 10 20H1 as a source and got the same issue with the missing file. However, with 20H1 with the notepad2 script removed and no third party notepad installed. I got it to open with regular notepad but did not say it was missing. I did check though and it was missing. 
![Capture](https://github.com/PhoenixPE/PhoenixPE/assets/34587652/9b6e79db-7412-4b8c-81db-2bb063266935)
![Capture1](https://github.com/PhoenixPE/PhoenixPE/assets/34587652/24112fdf-96dc-40de-a654-d15fceb12be2)

**Comment by homes32** [comment]
This was an interesting one. File attributes were being stripped (for over a year) now, however PECMD was either intentionally or unintentionally suppressing execution of the start menu Startup folder. This is not documented behavior. With the move to AU3 the desktop.ini files did not have the hidden and system attributes applied so it executed like a regular program. The file attributes have been corrected so this issue should no longer occur.

**Comment by schrebra** [comment]
You're awesome. Thank you for your time and dedication to an awesome project. I plan on trying out new releases in the future so I'll try to submit anything not working. :)

**Comment by Mikka-TheOne** [comment]
One last note before the issue is closed:

In the new release, I noticed that on the Desktop, in addition to shortcuts, the Desktop.ini file is also displayed (partially transparent due to the hidden attribute). I finally commented out line 477 in `001-Explorer.script`:
`RegWrite,HKLM,0x4,"Tmp_Default\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced","ShowSuperHidden",1`
If _Show Hidden & System Files_ is now ticked in `001-Explorer.script`, no Desktop.ini appears on the Desktop.

**Comment by homes32** [comment]
> One last note before the issue is closed:
> 
> In the new release, I noticed that on the Desktop, in addition to shortcuts, the Desktop.ini file is also displayed (partially transparent due to its hidden attribute). I finally edited line 477 in `001-Explorer.script`: `RegWrite,HKLM,0x4,"Tmp_Default\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced","ShowSuperHidden",0` If _Show Hidden & System Files_ is now ticked in `001-Explorer.script`, no Desktop.ini appears on the Desktop.

Easy enough to add as an option. I don't really like hidden/system/extensions lumped together anyway.

**Comment by Mikka-TheOne** [comment]
I'm using a personalised version of `001-Explorer.script` in MyApps.
Apart from special requirements for me (commented out lines), it also comes with a few useful changes for everyone.
They are indicated in the comments [_"(Mikka)"_]. I've attached it even if it's somewhat off-topic.

[001-Explorer_(mod).zip](https://github.com/PhoenixPE/PhoenixPE/files/14022341/001-Explorer_.mod.zip)
