### ISSUE TITLE
Iso boots and gets hung up at "Loading Display Drivers..."

### ISSUE THREAD

**Issue by VanFlusen** [PhoenixPE/PhoenixPE#77]
﻿

Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
I have created several iso's with Win11 22H2_22621.525 and Win11 23H2_22631.2428 on different machines with the default settings.

Two computers with Intel processor:

Iso boots and gets hung up at "Loading Display Drivers...".
The Task Manager cannot be started.
By pressing the "Enter" key several times, the process is continued and a desktop.ini is displayed on the desktop

![1](https://github.com/PhoenixPE/PhoenixPE/assets/82698833/01c092ae-4367-4c32-9ee3-c91c4f1fd8b4)

On an AMD Ryzen PC there is no problem with "Loading Display Drivers..." but a desktop.ini is also created.
I have run these tests several times!

I have added Auto Login as Admin and on Intel PC's Enter has to be pressed several times again.

AutoIt Error: The graphics mode is not supported.
![2](https://github.com/PhoenixPE/PhoenixPE/assets/82698833/39329204-d6b1-466c-b846-d85e347a0632)

And the well-known error from: #75

![3](https://github.com/PhoenixPE/PhoenixPE/assets/82698833/d273c793-e4f5-4cef-a7af-0bb2df2060e9)

On the Ryzen Pc there is no problem with "Loading Display Drivers..."
but: The current file has been deleted. Save now?

![4](https://github.com/PhoenixPE/PhoenixPE/assets/82698833/4d306202-b124-4782-99ec-ac1f9e84cd35)

**Comment by homes32** [comment]
Thank you for the screenshots. they were very helpful.

The error message blocking startup has been fixed, and the desktop.ini issue from #75 has also been corrected.

**Comment by VanFlusen** [comment]
Thank you for your excellent work and quick help.

It now works perfectly, except for one small detail.

After I switch from System to Admin there is the desktop.ini on the Admin desktop (Hidden file is displayed).

**Comment by Mikka-TheOne** [comment]
> After I switch from System to Admin there is the desktop.ini on the Admin desktop (Hidden file is displayed).

See [this comment](https://github.com/PhoenixPE/PhoenixPE/issues/75#issuecomment-1903893422) of mine for a solution.

**Comment by VanFlusen** [comment]
> Thank you for your excellent work and quick help.
> 
> It now works perfectly, except for one small detail.
> 
> After I switch from System to Admin there is the desktop.ini on the Admin desktop (Hidden file is displayed).

I have added Explorer.script 1.7.0.0 and booted it on 3 machines for testing.

The screen flickers between wallpaper and white screen until PhoenixPE is fully loaded.

When I run Switch user, I get a blue screen on 2 computers, Stop code : CACHE MANAGER

On a third machine I can run Switch user without any problems.

**Comment by homes32** [comment]
Stop 0x00000034 generally indicates low memory. How much RAM is in the machines where you get the BSOD?

I can usually reproduce this in VMware by setting memory a low vaule (2GB, sometimes 4GB) depending on running programs and the size of the user profile.

**Comment by VanFlusen** [comment]
I have installed Windows 11 on a test computer and unpacked PhoenixPE.
I have updated MMC.script, Core.script, PreShell.script and Explorer.script.
I only activated Logon as Admin and did not change the default settings.

1. booting with a Lenovo laptop (8 GB RAM) ends with BSOD after switch users.

2. booting with DELL Optiplex (16 GB RAM) ends with BSOD after switch users.

3. booting with AMD Ryzen (32 GB RAM) ends with BSOD after switch users.

In VMWare (8 GB) on AMD Ryzen, switch users does not cause any problems.

In VMWare (4 GB) on AMD Ryzen :

![Unbenannt](https://github.com/PhoenixPE/PhoenixPE/assets/82698833/1520fb03-57fa-4abe-ae56-363b5ffa643f)


![3](https://github.com/PhoenixPE/PhoenixPE/assets/82698833/362ff1a9-bc2b-4b93-a73d-ea2c45917ece)

**Comment by VanFlusen** [comment]
It is very strange and gives the impression that the BSOD is caused randomly on the different computers.
Computer boots and switch user causes BSOD and at a later time switch user works without problems.
You probably think I'm crazy and I'm beginning to believe it too.

**Comment by VanFlusen** [comment]
I boot PhoenixPE and wait 2-3 minutes before running switch user and it works fine on two machines.
Tested several times.
On a Lenovo ThinkPad (8 GB RAM) switch user still ends with a BSOD.
I have activated Auto Logon as Admin and there are no problems.

**Comment by homes32** [comment]
Let's move this into a different issue, as it's strayed pretty far from the original, which has been resolved. That way we can still track any progress if a pattern is discovered.
