### ISSUE TITLE
Wpeutil.exe now required to shut down PE (StartIsBack++ 2.9.19, Start10 1.56)

### ISSUE THREAD

**Issue by Mikka-TheOne** [PhoenixPE/PhoenixPE#78]
﻿**Initial situation**

I am using a current PhoenixPE release with Win10 2004 and testing the generated ISOs with VMware Player.

The tested shells are:

- Open-Shell Menu v4.4.191
- StartIsBack++ v2.9.19
- Start10 v1.56, a port of mine from Win10PESE

While Open-Shell Menu works as expected, a click on _Shutdown_ of StartIsBack++ or Start10 has no effect.
It's necessary to use `PhoenixPE.au3` for that.

**To reproduce**

1. Ticked scripts in Shell: PreShell, Explorer Shell, StartIsBack++
2. Carry out a new build
3. In PhoenixPE click on the orb to initiate the start menu
4. Select _Shutdown_

The menu closes, nothing else happens.
However this will work: Shutdown > _Reboot_

**Comment by Mikka-TheOne** [comment]
Since both StartIsBack++ and Start10 unfortunately show this bug, I customised Open-Shell a bit for my needs.
I used the Advanced Options of the script for using a XML file and got the following error:

![AutoIt_Error](https://github.com/PhoenixPE/PhoenixPE/assets/152649471/40498c32-e300-4d28-97f5-e3c2bba82eb6)

**Comment by homes32** [comment]
> I used the Advanced Options of the script for importing a XML file and got the following error:

That issue with the double-quotes was fixed last week. You will want to grab the latest version of the Pre-Shell script from the master branch and you should be good to go.

Have you opened a case with the author or StartIsBack++ or Start10 to see what API they are using for shutdown and if they made a change? StartAllBack from the same author as StartIsBack works correctly. I also noticed that  StartIsBack++ shutdown works if you switch to admin.  

Open-Shell uses InitiateShutdown() from Advapi32.dll for shutdown/reboot. No idea what the other 2 use as the source is not available.

**Comment by Mikka-TheOne** [comment]
I get this error (VM) using v1.0.1.0 of `000-PreShell.script` as long as _cb_UseCustomXMLCfg_ is used.
Haven't tried `LogonAsAdmin.script` so far, but I will (for StartIsBack++).
This problem wasn't present in the previous version of PhoenixPE (same version of StartIsBack++).
As for Start10, I've adopted an outdated version (which did fine before, though).
Prior to contacting the author, I'd have to update it first.

**Comment by homes32** [comment]
> I get this error (VM) using v1.0.1.0 of `000-PreShell.script` as long as _cb_UseCustomXMLCfg_ is used. 

Sorry, I neglected to mention you also need to grab the phoenixAPI script To fix the custom config.

**Comment by Mikka-TheOne** [comment]
> the phoenixAPI script

I'm using version 1.9.2.0 of `PhoenixAPI.script`.

**Comment by homes32** [comment]
> > the phoenixAPI script
> 
> I'm using version 1.9.2.0 of `PhoenixAPI.script`.

The changes are in PhoenixAPI 1.9.3.0
I have also updated the release 2024.02.09 to roll up all these fixes.
