### ISSUE TITLE
Much hassle with wireless network auto connection

### ISSUE THREAD

**Issue by Mikka-TheOne** [PhoenixPE/PhoenixPE#79]
**Initial situation**
I'm using the current PhoenixPE release with Win10 2004 on one notebook with wireless network connection.
While I succeeded in making it work for the previous version after long testing, the same difficulties now occur again.
Since this version there is one script for networking and one for the auxiliary tool PENetwork.

**Steps to localise the problem(s)**
1. First of all, network connectivity/drivers, WLAN credentials, script settings, all have been checked.
2. Running NetShell (e.g. `netsh wlan show interfaces`) resulted in error messages about DLL files that could not be loaded.
So I added missing _netsh_ dependencies to `310-Networking.script` including:
nshhttp.dll, nshipsec.dll, peerdistsh.dll, rpcnsh.dll, whhelper.dll, [wwancfg.dll], wwapi.dll
3. In my custom `PENetwork.ini`, in section `[Auto Connect Wifi]` I verified the line `CMDStart.Wait3=Yes`
4. In the `310-PENetwork.script` I added `#$q` (quotes) to the variable `%SSID_name%` (line 159)

Initially, no wireless connection is established, a taskbar icon shows: status offline.
I then run the command `netsh wlan show profiles` and get:
```
Profiles on interface Wi-Fi:

Group policy profiles (read-only)
---------------------------------
    <None>

User profiles
-------------
    <None>
```

Entering the CMDStart.CMD3 line of `PENetwork.ini` manually, e.g.
`netsh wlan add profile filename="X:\Program Files\PENetwork\WifiProfiles\wlan-credentials.xml" user=all`

```
The profile My Wi-Fi is added to the Wi-Fi interface.
```
The wireless connection starts up immediately and a wifi icon appears on taskbar.
So apparently, CMDStart.CMD4 has been applied already, but CMDStart.CMD3 has not.

As a result I now get the expected output for `netsh wlan show profiles`:
```
Profiles on interface Wi-Fi:

Group policy profiles (read-only)
---------------------------------
    <None>

User profiles
-------------
    All User Profile    : My Wi-Fi
```

However something is still missing in order to automatically connect to the wireless network when loading the desktop.

**Comment by homes32** [comment]
I added the netsh dependencies you listed and the quotes around the SSID name in https://github.com/PhoenixPE/PhoenixPE/commit/fcd09d665c607a46c9c5292a2fe4b402bda36d86. tested win 10 2004 and I get my wireless connection auto started properly on boot. tested with spaces in the path and without. If you don't mind, try building again with the updated scripts and see if perhaps the dependencies solved the issue.

**Comment by Mikka-TheOne** [comment]
It now does work if I just specify the Wifi profile.
Apparently there is a negative impact between an existing `PENetwork.ini` and the `310-PENetwork.script`, I can't tell which settings these are. The safe bet is having the `PENetwork.ini` generated by the script. I made a copy of `310-PENetwork.script` and adjusted two settings, it's still functional.

**Comment by Mikka-TheOne** [comment]
The colour scheme looks like having a negative influence, instead of "Default" I had selected "Win10_GUI_Colored".

**Comment by homes32** [comment]
Can you list your steps to reproduce? I can't seem to get the same behavior.
