### ISSUE TITLE
Both Brave Browser and Windows (defender?) not allowing download of latest version

### ISSUE THREAD

**Issue by TryTryAgain** [PhoenixPE/PhoenixPE#80]
When trying to download the file https://github.com/PhoenixPE/PhoenixPE/releases/download/2024.01.14/PhoenixPE-2024-01-14-x64.7z in the Brave Browser it's getting denied because of "dangerous file" and then even if I force it to download Windows is also then immediately removing it as "virus".

**Comment by homes32** [comment]
https://github.com/PhoenixPE/PhoenixPE/wiki/Security#anti-virus-false-positives
