### ISSUE TITLE
Camara suport

### ISSUE THREAD

**Issue by fgaifen** [PhoenixPE/PhoenixPE#81]
Hi.
So I'm tying latest releases and it works very well.
In some things is better than WIN10XPE, in other things is still need a lot of work.
For my daily use is still lacking a few features like Camera support.
I've tried to change my win10xpe script to your project. So files are copied, but is something wrong with registry because camera will be with exclamation mark.
Can you help?
here is link to my script: https://bc141b.s.cld.pt

**Comment by homes32** [comment]
Your not far off. Let me look at this in more detail tonight. 

What is your case case for camara support in WinPE?

**Comment by fgaifen** [comment]
I work in a "laboratory" where we perform computer and cell phones repairs.
I've managing a closed project of a boot usb drive for testing computer hardware and operating systems install (like ventoy or aioboot...) and testing a web cam is one of the needs.
So I was using win10 1809 pe based on win10xpe project because camera only worked until that version.
The camera subject was a few times mentioned but only when one of the users manage to give me a copy of "kuer pe" I manage to create a working script for all windows 10 / 11 versions. But I can't make it work with your project and I believe that will bring so many  users for this project.
Best regards

**Comment by homes32** [comment]
Please test [this script](https://github.com/PhoenixPE/PhoenixPE/blob/master/Projects/PhoenixPE/Components/Camera.script) and see how it goes. It's working for me Win10 2004 and Win11 23H2 with a Logitech webcam. Tested with OBS Studio and ECap.

Thanks for sharing your use case. It's always nice to hear/see how others are using the project and various components/apps.

**Comment by fgaifen** [comment]
Hi.
Tested now with win11 22h2 22621.2428 and win10 22h2 19045.3803 (both x86 and x64) and is working greate.
