### ISSUE TITLE
wmic broken when using SlimFast "710-SlimFast.script"

### ISSUE THREAD

**Issue by Whatslp** [PhoenixPE/PhoenixPE#83]
Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------

the following entry must be removed from "﻿710-SlimFast.script":
DirDeleteEx,"%TargetSystem32%\wbem\xml"

**Test:**
wmic ComputerSystem Get Model /value

**Output without the directory:**
Node - PhoenixPE
ERROR:
Description = Generic failure

**Comment by homes32** [comment]
Fixed. Thanks for the report!
