### ISSUE TITLE
Administrator Account Bug

### ISSUE THREAD

**Issue by fgaifen** [PhoenixPE/PhoenixPE#84]
﻿

Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
﻿With Administrator accont devmgmt.msc can't access registry to install drivers, access denied will appear.
It's working without Administrator account
Only using NSUDO will be possible to install drivers with Administrator account.

**Comment by homes32** [comment]
What source version are you using?

**Comment by fgaifen** [comment]
I'm using w11 10.0.0.22621.2420 and tested now with w10 10.0.019045.4046, and problem is in both builds.

**Comment by fgaifen** [comment]
It's very difficult to repply in theoven.org so I'll user this:
Now my robocopy script is working (I really don't know why it was not) but the rest of the problems still persist: "With Administrator accont devmgmt.msc can't access registry to install drivers, access denied will appear" and I found another bug: buit-in windows drivers are not installing, for example using MTP or Bluetooth scripts I still need to search for drivers in a intalled system (C:\Windows\System32\DriverStore\FileRepository).
You say that "everyone" will be in every project but this project is the only one that has only "everyone " as security. The other projects will have also "System", "Users" and "Administrators.
For buit-in drivers I found a workaround: I created a script that run dism and process all FileRepository before Drivers scripts but as I said this is only a workaround.

**Comment by homes32** [comment]
Any chance you de-selected the "Take full ownership of the Software hive" advanced option in the Core Registry script?

So far I have not had any luck reproducing the issue. Any other information you can provide? type of device you are installing? steps to reproduce? screenshots?

**Comment by fgaifen** [comment]
So, I download master again and make tests in an unmodified "buid".
Unchecking "Take full ownership of the Software hive" I have errors in shell-config script in "Personalize"section and wow64 script has to be disabled, also explorer script give errors so it's impossible to do buid a image in this condition...
These are the screenshots:
![configuration](https://github.com/PhoenixPE/PhoenixPE/assets/47121387/e1aae59c-3d93-4014-8275-01be0b2b9b3b)
So de device I'll try to install is a specific controler for ARGB in ASUS mainboards wich is isntalled by winusb.inf
Trying to install using current drivers (will give error: "specific file isn't found" (I'm using Portugues windows so I'm trying to translate).
![vmware2](https://github.com/PhoenixPE/PhoenixPE/assets/47121387/6c9473d5-dfb4-4c5d-a01f-21e0e8fd6957)
![vmware3](https://github.com/PhoenixPE/PhoenixPE/assets/47121387/f3892347-c76d-4d5e-b908-4e87476b4167)
Using an installed windows in drive c:
![vmware4](https://github.com/PhoenixPE/PhoenixPE/assets/47121387/6d298a61-83c9-4e86-bc20-74f9f2115fef)
Acces denied:
![vmware5](https://github.com/PhoenixPE/PhoenixPE/assets/47121387/631627ab-a2ce-49b0-bfcb-07487145e72b)
Using Nsudo:
![vmware6](https://github.com/PhoenixPE/PhoenixPE/assets/47121387/926fa5b6-5723-473d-99c2-6a417929800b)
![vmware7](https://github.com/PhoenixPE/PhoenixPE/assets/47121387/0374d06c-bb77-4cb4-8349-e1840ee7ba0e)
Has the hability to install but fail becouse digital signature....
Adding the driver by dism or changing bcd to testsigning off will work.

So my conclusion is that a device that needs built in drivers totally or partially will fail to install.

Also, I defined administrator account name to FG but the name was notr changed
![admac1](https://github.com/PhoenixPE/PhoenixPE/assets/47121387/b5b908cc-668d-46d4-8065-66b15ec6c2c6)
![admac2](https://github.com/PhoenixPE/PhoenixPE/assets/47121387/39abe35c-f251-444f-bd7e-ee0870ed09a9)

**Comment by fgaifen** [comment]
![admac2](https://github.com/PhoenixPE/PhoenixPE/assets/47121387/84ee2a0d-4765-45da-80ed-5fa040481af8)

**Comment by homes32** [comment]
Thanks for the additional info. Is it possible that you have some Antivirus/EDR system interfering with the build? I have heard of cases where an antivirus blocks registry operations.

I also have an ASUS board with the AURA controller and it installs perfectly, either integrated with DISM or manually through devmgmt.msc

If I change the admin name to FG on a stock build it works fine for me. 
What does your `X:\Windows\security\logs\unattend.log` log say?

I'll have to see if I get any different results with a Portuguese ISO.

**Comment by fgaifen** [comment]
Strange because I'm using same build in other projects and I have defender  with exceptions folder configurated.
Log sya everything is ok but name doesn't change.
I'll atach all logs gereneted
[PhoenixPE.log](https://github.com/PhoenixPE/PhoenixPE/files/14568514/PhoenixPE.log)
[unattend.log](https://github.com/PhoenixPE/PhoenixPE/files/14568515/unattend.log)
[winpeshl.log](https://github.com/PhoenixPE/PhoenixPE/files/14568516/winpeshl.log)
[wpeinit.log](https://github.com/PhoenixPE/PhoenixPE/files/14568517/wpeinit.log)

**Comment by fgaifen** [comment]
Done a few tests now with both w11 and w10.
Aura controller still not installing (access denied error), Bluetooth and mtp only install if I use "install.wim" as drivers hive and mtp is giving error, I saw that mtphelper.sys is copyed to system32\drivers\mthelper.sys\mtpxxx.sys and not to system32\drivers\mthelper.sys. Appart from that also says that  a class is missing.
Administrator accout name still not change in explorer or cmd. I really don't know why is not changing.
Tested also with english versions.

**Comment by homes32** [comment]
I'm getting a 404 trying to view the logs you linked to. Can you re-attach?

The good news is that I found the bug in the MTP script that extracts the mthelper driver to the wrong directory. Thank you for reporting that!

**Comment by fgaifen** [comment]
[PhoenixPE.log](https://github.com/PhoenixPE/PhoenixPE/files/14584030/PhoenixPE.log)
[unattend.log](https://github.com/PhoenixPE/PhoenixPE/files/14584031/unattend.log)
[winpeshl.log](https://github.com/PhoenixPE/PhoenixPE/files/14584032/winpeshl.log)
[wpeinit.log](https://github.com/PhoenixPE/PhoenixPE/files/14584033/wpeinit.log)

If any problem downloading I put also in my cloud:
https://hp5dir.s.cld.pt

**Comment by fgaifen** [comment]
Despite my effort adding and removing registry entries it remains the same.
Also this is what is happening:
![PhoenixPE_accounts](https://github.com/PhoenixPE/PhoenixPE/assets/47121387/f7566ae3-256e-44b9-8eb8-85938f16ecde)
Accont name changes using net user but registry entries and accont name in explorer doesn't.

**Comment by fgaifen** [comment]
So I've done a lots of tests and make a workaround for my case.
I "discovered" that without "Logon as Admin" script pe will boot into system account.
Registry hive SAM is available so, i add this to Phoenixpe.au3 in Func SwitchToAdmin:
; Delete Buit-in Administrator account
RegDelete("HKLM\SAM\SAM\Domains\Account\Users\Names\Administrador")

Then I created a cmd wich creates my desired administrator account (I try to do it autoit but I was stuck trying to create an account with more than one word):
NET user /add "Cl¡nica Fnac"
NET localgroup administradores "Clínica Fnac" /add

And add it to "Logon as Admin" script to extract to system32 and add this to Phoenixpe.au3:
; Create wanted Adminitrator account
RunProgramWait('%WINDIR%\SYSTEM32\ADM.cmd', '', '', @SW_HIDE)

Doing this not only I manage to create my desirable Administrator account but also my problem with drivers and access denied is solved.

Problem with buit-in drivers not installing without dism or in case of bluetooth the need to use install.wim as drvers hive still persists.
