### ISSUE TITLE
PhoenixPE-UserConfig.au3 not run

### ISSUE THREAD

**Issue by QuyBao2** [PhoenixPE/PhoenixPE#85]
file path error in boot.wim ( windows/system32/PhoenixPE.au3)
file PhoenixPE.au3
If FileExists(@SystemDir & "\PhoenixPE-UserConfig.a3x") Then RunProgram(@SystemDir & "\AutoIt3.exe", @SystemDir & "PhoenixPE-UserConfig.a3x")
If FileExists(@SystemDir & "\PhoenixPE-UserConfig.au3") Then RunProgram(@SystemDir & "\AutoIt3.exe", @SystemDir & "PhoenixPE-UserConfig.au3")

file path error, fix manually  missing "\"  "PhoenixPE-UserConfig.a3x" -->"\PhoenixPE-UserConfig.a3x" 

Is there a way to make it run automatically, when building ?

**Comment by homes32** [comment]
Fixed in [5db0b96](https://github.com/PhoenixPE/PhoenixPE/commit/5db0b96e6a8e7e1bf1444d3584412f5f103b6a94). Please try the latest  000-PreShell.script

**Comment by QuyBao2** [comment]
> Đã sửa lỗi trong [5db0b96](https://github.com/PhoenixPE/PhoenixPE/commit/5db0b96e6a8e7e1bf1444d3584412f5f103b6a94) . Vui lòng thử 000-PreShell.script mới nhất

Thank you very much !
