### ISSUE TITLE
Hardrive local partition and dual boot 

### ISSUE THREAD

**Issue by lodarmayarder** [PhoenixPE/PhoenixPE#87]
﻿

Checklist
---------
- [x] I performed a search in the issue tracker to see if my suggestion has already been asked/answered by somebody else.

**Describe the solution you'd like**
Automatic creation of a partition containing the project.
Partition added to bcd entry for booting PhoenixPE

**Describe why you believe your suggestion would benefit the project and members of the community at large**
This would allow the project to be protected within a partition.
To have a local custom WinRe for maintenance.

**Describe alternatives you've considered**

**Additional context**

Thank you for the work, congratulations on the latest advances (Autoit...)

**Comment by homes32** [comment]
I like the concept, but messing around with peoples partition tables isn't something I want to get into. Too many different disk configurations and things that could go wrong. For now the PhoenixPE > Testing > Host Boot option is the closest to this I can offer (and really the same concept minus the partition to hide everything away.
