### ISSUE TITLE
firefox spits out errors

### ISSUE THREAD

**Issue by progamer562** [PhoenixPE/PhoenixPE#88]
![image](https://github.com/PhoenixPE/PhoenixPE/assets/75967844/ba6f862e-bcda-4412-bf81-b348d36693b8)

[Error] [E] RegWrite - Attempted to perform an unauthorized operation. (RegWrite,HKLM,0x1,"Tmp_Software\Microsoft\Windows\Shell\Associations\UrlAssociations\http\UserChoice","ProgId","FirefoxURL") (Line 362)

[BuildLog.log](https://github.com/PhoenixPE/PhoenixPE/files/15071352/BuildLog.log)

**Comment by kevinwijnb** [comment]
I believe it's fixed in this commit:


https://github.com/PhoenixPE/PhoenixPE/commit/f2d1073e38d52025b63bb33c32e54c2f0c013786

**Comment by progamer562** [comment]
it works
