### ISSUE TITLE
Open-Shell Settings not being applied

### ISSUE THREAD

**Issue by webmogul1** [PhoenixPE/PhoenixPE#9]
Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
I had to change the open-shell script otherwise xml settings would not be applied.

`AddAutoRun,PostShell,Wait,"Configuring Open-Shell Menu...","#$pProgramFiles#$p\Open-Shell\StartMenu.exe","-xml MenuSettings.xml"`
`AddAutoRun,PostShell,NoWait,"Configuring Open-Shell Menu...","#$pProgramFiles#$p\Open-Shell\StartMenu.exe"`

**Comment by homes32** [comment]
fixed. thanks for reporting.

**Comment by webmogul1** [comment]
Thank you!
