### ISSUE TITLE
download all needed files before starting the build process

### ISSUE THREAD

**Issue by rezad1393** [PhoenixPE/PhoenixPE#91]
Checklist
---------
- [x] I performed a search in the issue tracker to see if my suggestion has already been asked/answered by somebody else.

**Describe the solution you'd like**
right now this app downloads ans install (and configures) apps one by one.
and the build process is not a fast process.
I have a restricted internet that has connection issues so if in the middle of the build a needed app cant be downloaded the build process is stopped (error) and I need to find what packages is not downloaded.

the better way would be to separate the download step of build from the rest.
so that the whole packages get downloaded (as much as is possible) first, then build happens.

**Describe why you believe your suggestion would benefit the project and members of the community at large**
helps people like me that have flaky internet.
 also makes the process cleaner.

**Describe alternatives you've considered**

**Additional context**

also can I manually download an installer of an app that PhoenixPE cant download at build time and put it somewhere so that instead of downloading it again it finds it locally?

**Comment by homes32** [comment]
Hi!,

In addition to saving bandwidth, PhoenixPE's cache was built with situations like this in mine.

On each app script that needs to download files, you will find a download button on the top right. You can use this button to pre-download any scripts you wish to use. They will be cached in `<PhoenixPE Root Dir>\Workbench\PhoenixPE\Programs` and used in subsequent builds. Programs downloaded during build time will also be cached in the same location and used in subsequent builds.

I can't possibly determine what each person wants in their build or what their internet situation is, so the individual download buttons are the best solution, even if it means a bit of work ahead of time for the builder if you need to go this route.

Since PEBakery and PhoenixPE are fully portable, it is also possible to place the PhoenixPE install directory on a USB drive or portable hard drive, plug in at someplace with a faster/more reliable internet connection and launch PEBakery to pre-download the apps you need. 

As a last resort, you can also download an installer manually and place it in the correct cache folder, but you must know exactly which path and file name that the script will be looking for, so this is best left for expert users who fully understand what each script wants.

**Comment by rezad1393** [comment]
> In addition to saving bandwidth, PhoenixPE's cache system was built with situations like this in mind.

I understand this and I like it, but I meant before starting the build the app should download all the needed files first so that network issues dont interfere with build process (Which takes a long time)


> I can't possibly determine what each person wants in their build or what their internet situation is, so the individual download buttons are the best solution, even if it means a bit of work ahead of time for the builder if you need to go this route.

why not?
when I select and deselect option to install and then press build the app does download the needed files first right?
it is just that the download and build part of every packages is done one by one.

does the app not download the sources for a module first and then build it?

if you dont want to change the flow of app you can just make a simple change that make the app go through all the selected modules and just run download part first then go from start again and run the build (+download ) ?

the second time download part is run they are cached so they dont halt the build with possible network errors. it is redundant but I just wanted to change the first step so as not to change the whole app flow.

what I mean is maybe make it possible to make dry run first that just downloads and caches the file then make the second run that downloads (but they are cached so no error) and build the image.

**Comment by homes32** [comment]
> if you dont want to change the flow of app you can just make a simple change that make the app go through all the selected modules and just run download part first then go from start again and run the build (+download ) ?

PEBakery (the build engine) does not work like that. each script is it's own independent module executed in sequence batch style.

> what I mean is maybe make it possible to make dry run first that just downloads and caches the file then make the second run that downloads (but they are cached so no error) and build the image.

This is exactly what you get if you use the download button first on each script you want to include. Once you do this and the setup files are cached the internet is no longer required.

**Comment by rezad1393** [comment]
> This is exactly what you get if you use the download button first on each script you want to include. Once you do this and the setup files are cached the internet is no longer required.

not really?
first: the way you meant it is manual not automatic.
they are a lot of them and running them all manually is not really good. 
second: I mean that the first time just download happpens not build.
clicking the individual modules download and builds them that take a lot of time. my solution is to just run the download part (if it is possible) and stop after that and not run build part for the module.

**Comment by josephworks** [comment]
Some modules are programmed to download and build regardless of caching. Also, if you download and build once (and the scripts are programmed with caching in mind) then sequential builds will be faster.

Could you share some information of which scripts are taking a while to build and maybe attach them to the message?

**Comment by rezad1393** [comment]
all the build process is slow cause I run it inside a windows VM, as I culdnt use this app on a winpe enviroment..
so I just wanted to be sure I dont get network error before running the build so that I dont have to wait for all that time over and over.


btw the image I create doesnt run on my laptopt and crashes a the windows start
. but the winpe-10-8-sergei-strelec-english runs.

**Comment by homes32** [comment]
> Some modules are programmed to download and build regardless of caching.

The only downloads that are not cached during build are a few scripts like simplewall or PCI-Z where there is an option to download additional ruleset updates at build time. These optional updates can be turned off on the applicable script's interface. Program files are always cached unless you select the option to "Always Download" on scripts that support it. Even then the files are cached after being downloaded, that script's cache just gets cleared every run if the checkbox is selected, forcing a new download.

**Comment by rezad1393** [comment]
I think I close this as caching is done and I think I just fix the network issues one by one.
