### ISSUE TITLE
IntelMEIDriver.script overwrites the driver everytime

### ISSUE THREAD

**Issue by rezad1393** [PhoenixPE/PhoenixPE#92]
Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
every time I try build, at the driver part of image the IntelMEIDriver driver gets downloaded every time from start.
it is a big file 700MB so it is very annoying.

**Describe what is happening**
IntelMEIDriver gets overwritten and downloaded from start at every build.
 

**To Reproduce**
select the IntelMEIDriver driver to be included.
click build.
at the driver part the driver gets downloaded

**Expected behavior**
it should be cached

**Screenshots/Logs**
If applicable provide any error messages, log files, screenshots, scripts, etc. that may be helpful for troubleshooting or further explain your issue.

**Comment by homes32** [comment]
yup. that should absolutely be cached. Fixed in 2241559
