### ISSUE TITLE
Windows 10 x86 result in a non functional system

### ISSUE THREAD

**Issue by fgaifen** [PhoenixPE/PhoenixPE#95]
Checklist
---------
- [X] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [X] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
I've tryed build a windows 10 x86 PhoenixPE and none of the isos will boot properly.

I used the following windows 10 x86 versions with the following results:
10.0.19041.2965 - BSOD 0xc0000119 and then it shutdowns
10.0.19041.1 - reboots before preshell
10.0.19045.4529 - reboots before preshell

A few months ago, when Camera script was published worked so something has changed.

Tests were made with default configuration without any change in scripts or in selected programs using last release.

**Comment by homes32** [comment]
there is no such thing as BSOD `0xc0000119`. (see https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-code-reference2). if you meant to say `0x00000019` that's a memory issue. If your testing in VMware/virtualbox/etc. increase your RAM. If you meant `0x00000119` that's a video driver issue.

**Comment by fgaifen** [comment]
My fault it's 0xc0000139.

![BootPack-2024-06-25-01-22-32](https://github.com/PhoenixPE/PhoenixPE/assets/47121387/405d4292-2cf0-4874-9901-d561cec8ba0f)

![Captura de ecrã 2024-06-25 012400](https://github.com/PhoenixPE/PhoenixPE/assets/47121387/50f7764e-2073-4fad-8eec-14d9d29a6672)

**Comment by homes32** [comment]
It still seems like there is a resource issue/conflict with vmware. have you tried running on a physical machine?

**Comment by fgaifen** [comment]
I tested it now and unfortunately the result is the same.
Also the builds were made with last master version,

**Comment by fgaifen** [comment]
Hi.
Commit 7896dff solve the problem.

**Comment by homes32** [comment]
awesome. thank you for following up!
