### ISSUE TITLE
Trying to build from a mapped drive results in error.

### ISSUE THREAD

**Issue by PCAssistSoftware** [PhoenixPE/PhoenixPE#96]
Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------

Trying to build from a mapped drive results in error.

Basically all my files are stored on a NAS, so I have a mapped drive (Y:) to the base folder "WB" which contains PhoenixPE folder and another folder containing my Windows 11 source files.

If I try to build get error as shown in screenshot below

![image](https://github.com/PhoenixPE/PhoenixPE/assets/10872799/df3326f7-22c9-494f-8809-659b65d22f98)

Is there any reason why it can't be change to allow building from a network share rather than having to copy all the files to my local drive?  NAS share is just as quicker as local drive.

If not possible then not to worry, but thought I would ask.

P.S. keep up the great work!

**Comment by homes32** [comment]
From your screenshot, it looks like you are building from a UNC path, not a mapped drive.

`System,GetFreeSpace` uses the `GetFreeSpace` property of `DriveInfo()` which requires a drive root path.

You can disable the free space check under Pre-Flight Check > Advanced Options

**Comment by PCAssistSoftware** [comment]
Hi, thanks for response.

I will give it a try with free space check turned off and report back shortly.

Definitely running from a mapped drive (Y:), I was confused as to why the first yellow warning shows a UNC path when I am running PE Bakery from Y:

**Comment by PCAssistSoftware** [comment]
Gets a lot further with the free space check disabled but still fails, this time with error below, which again confuses me as clearly showing a UNC path in the error message when I am running from a mapped network drive (Y:)

[Error] [E] FileCopy - Could not find a part of the path '\\192.168.1.100\Storage\WinBuilder\PhoenixPE\Workbench\PhoenixPE\Temp\Open-Shell\SourceDir\StartMenuHelper64.dll'. (FileCopy,"%ProjectTemp%\%ProgramFolder%\SourceDir\StartMenuHelper64.dll",%TargetSystem32%) (Line 123)

![image](https://github.com/PhoenixPE/PhoenixPE/assets/10872799/47152c6b-b12d-47d2-89a4-1e1dd02312e6)

**Comment by homes32** [comment]
Can you please post the support log .7z file from the logs dir?

**Comment by PCAssistSoftware** [comment]
attached
[2024-06-25-2207-PhoenixPE-Logs.zip](https://github.com/user-attachments/files/15980105/2024-06-25-2207-PhoenixPE-Logs.zip)

**Comment by homes32** [comment]
Thanks!
Looks like this new issue might be a bug in [lessmsi](https://github.com/activescott/lessmsi) 

the command executed was 
```
ShellExecute - Executed [\\192.168.1.100\Storage\WinBuilder\PhoenixPE\Projects\PhoenixPE\Tools\anycpu\lessmsi\lessmsi.exe x "\\192.168.1.100\Storage\WinBuilder\PhoenixPE\Workbench\PhoenixPE\Temp\Open-Shell\OpenShellSetup64_4_4_191.msi" "192.168.1.100\Storage\WinBuilder\PhoenixPE\Workbench\PhoenixPE\Temp\Open-Shell\"]
```

but stdout from lessmsi is reporting:
```
Extracting '\\192.168.1.100\Storage\WinBuilder\PhoenixPE\Workbench\PhoenixPE\Temp\Open-Shell\OpenShellSetup64_4_4_191.msi' to '\\192.168.1.100\Storage\WinBuilder\PhoenixPE\192.168.1.100\Storage\WinBuilder\PhoenixPE\Workbench\PhoenixPE\Temp\Open-Shell'.
1/35	ClassicExplorer32.dll
2/35	ClassicExplorerSettings.exe
3/35	ClassicIE_32.exe
...
```

notice the mangled destination path?
```
\\192.168.1.100\Storage\WinBuilder\PhoenixPE\192.168.1.100\Storage\WinBuilder\PhoenixPE\Workbench\PhoenixPE\Temp\Open-Shell
```

**Comment by homes32** [comment]
actually, just noticed something else....

CTrim is also removing a leading `\\` from the DestDir and thats's whats confusing lessmsi

```
StrFormat - Local variable [%DestDir%] set to [192.168.1.100\Storage\WinBuilder\PhoenixPE\Workbench\PhoenixPE\Temp\Open-Shell] (StrFormat,CTrim,%DestDir%,"\","%DestDir%")
```

that's going to cause problems in a few scripts if your trying to run from a UNC path.

haven't had a chance to see why PEBakery is resolving the mapped drive to a UNC path though...

**Comment by PCAssistSoftware** [comment]
Thanks for looking, please don't waste too much (if any) time on this, I can always move the files to a local drive to run them, it was just first time I had run it since moving a lot of my not regularly used data to a NAS to solve space issues.

**Comment by homes32** [comment]
I've made a few changes that should hopefully help. If you want to test, you can download the updated scripts from the master branch. You will also need to compile (or use the artifacts) the latest development snapshot of PEBakery in order to gain access to the new `StrFormat` commands used.

**Comment by PCAssistSoftware** [comment]
Thanks.  More than happy to do some testing.  

Have downloaded latest nightly from https://ci.appveyor.com/project/ied206/pebakery/branch/develop/artifacts and all the updated scripts.  

But for some reason it won't even accept my source now (which was perfectly valid before), says "Please select a valid source", and looking at logs shows "[Error] Error - Invalid StrFormatType [EndTrim] (Line 125)"

Any thoughts?

**Comment by PCAssistSoftware** [comment]
Thanks. More than happy to test.  Will do so now and then report back :)

**Comment by PCAssistSoftware** [comment]
Testing update: failed with error "[Warning] Halt - Error: Dism.exe terminated with error code: [161]. Check the log for details. (If,Not,#r,Equal,0,Halt,"Error: Dism.exe te
[2024-06-29-2205-PhoenixPE-Logs.zip](https://github.com/user-attachments/files/16042203/2024-06-29-2205-PhoenixPE-Logs.zip)
rminated with error code: [#r]. Check the log for details.") (Line 146)"  - support logs attached

**Comment by homes32** [comment]
Crap! I was worried about that. Well, it was worth a shot anyway. Probably not worth messing around with much more at this point.

**Comment by PCAssistSoftware** [comment]
Agreed, thank you for trying though
