### ISSUE TITLE
Could not grant full permission 

### ISSUE THREAD

**Issue by lodarmayarder** [PhoenixPE/PhoenixPE#97]
﻿

Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
﻿

**Describe what is happening**
An error systematically occurs during construction.
It returned ''error:Could not grand full permission on''.

**To Reproduce**
Step-by-step instructions on how to reproduce the behavior : 
Build

**Expected behavior**

**Screenshots/Logs**
If applicable provide any error messages, log files, screenshots, scripts, etc. that may be helpful for troubleshooting or further explain your issue.

**Comment by homes32** [comment]
Hello,

you have not provided any useful information that could help us understand or determine the problem you are having.

Please provide the exact error message (preferably a screenshot) and the support log. (located in the Logs directory where you have PhoenixPE installed).

my best guess based on the incomplete error message you posted is that your antivirus software has deleted SetACL.exe from the tools directory or something has blocked it from accessing the registry.

**Comment by lodarmayarder** [comment]
The command returned : 3. 
The référence script is phoenix-pe api
∆I have restore all permission on file and folder. 
✓I have deleted the ligne in api script. The error IS bypass but ISO are not fonctionnaly.

**Comment by homes32** [comment]
Error 3 is an incorrect parameter.  Please attach your full build log.

**Comment by lodarmayarder** [comment]
I attach last log 
[BuildLog.log](https://github.com/user-attachments/files/16496148/BuildLog.log)

**Comment by homes32** [comment]
Thank you for the log.

```
[Success] [M] ShellExecute - [Standard Output] Retrieving the remote path for mapped drive L<\PE\Workbench\PhoenixPE\Target> failed with: Cette demande n’est pas prise en charge. (ShellExecute,Hide,%Tools%\%HostArch%\SetAcl.exe," -ot #$qfile#$q -on #$q#1#$q -actn ace -actn setprot -op #$qdacl:p_nc#$q -ace #$qn:S-1-1-0;p:full;s:y#$q")
      [Success] [M] ShellExecute - [Standard Error] ERROR while processing command line: object (name, type): C:\PE\Workbench\PhoenixPE\Target could not be set! (ShellExecute,Hide,%Tools%\%HostArch%\SetAcl.exe," -ot #$qfile#$q -on #$q#1#$q -actn ace -actn setprot -op #$qdacl:p_nc#$q -ace #$qn:S-1-1-0;p:full;s:y#$q")
      [Success] [M] If - [3] is bigger than [0] (If,Not,%ExitCode%,Equal,0,Halt,"Error: Could not grant full permission on#$x#$x#1#$x#$xThe command returned: [%ExitCode%].")
        [Warning] [M] Halt - Error: Could not grant full permission on

C:\PE\Workbench\PhoenixPE\Target

The command returned: [3]. (If,Not,%ExitCode%,Equal,0,Halt,"Error: Could not grant full permission on#$x#$x#1#$x#$xThe command returned: [%ExitCode%].") (Line 1727)
```

`Retrieving the remote path for mapped drive L<\PE\Workbench\PhoenixPE\Target>` is telling us the error returned by SetACL is in regard to not being able to resolve a network path. I'm inclined to think this is a bug in SetACL.exe as we can see your path is on the local drive. `C:\PE\Workbench\PhoenixPE\Target`

I found a couple of other similar cases on the SetACL FAQ. They seemed to be related to not having internet access. Do you have internet access on the computer you are building from? or perhaps multiple active network cards (physical or virtual)? If we can find a correlation I can reach out to Helge and see if he can fix the issue.

**Comment by lodarmayarder** [comment]
Thank you, I have access to the Internet and several network cards. 

Indeed, I tried building from the C: drive.

**Comment by lodarmayarder** [comment]
Thank you, I have access to the Internet and several network cards. 
Indeed, I tried building from the C: drive.

**Comment by homes32** [comment]
can you try disabling all network adapters except the primary (the one with your internet connection) and see if it makes a difference?

**Comment by lodarmayarder** [comment]
Hello,

All network cards have been disabled, the same error is encountered. I will try to look more closely at Setacl. Do you know if there is an alternative to this software?

**Comment by lodarmayarder** [comment]
Hello,

yo follow up on the problem, reinstalling windows fixed the problem. Thanks again for the research

**Comment by homes32** [comment]
Thanks for the update!

**Comment by sadsayeed** [comment]
I've been facing the same problem for ages... "Could not grand full permission on", exact same scenario, with no solution. I didn't want to re-install the entire OS just to fix this. 

So, I found out an easier solution rather. Just enable and start the 'Webclient' service in Windows Services. That fixed the "Could not grand full permission on" problem for me.

**Comment by homes32** [comment]
@sadsayeed Just wanted to say thanks for posting your solution. It seems to be working for others as well and mostly seems to have affected users running Win10 LTSC 2021.
