### ISSUE TITLE
Some application language options are incorrect

### ISSUE THREAD

**Issue by ninja0210** [PhoenixPE/PhoenixPE#99]
~\Applications\File Managers\7zip.script at line 611: "Chinese (Traditional) [zh-CN]","Chinese (Simplified) [zh-TW]"
should be -> "Chinese (Traditional) [zh-TW]","Chinese (Simplified) [zh-CN]"

~\Applications\Networking\Firefox.script at line 532:"Chinese (Traditional) [zh-CN]","Chinese (Simplified) [zh-TW]",
should be -> "Chinese (Traditional) [zh-TW]","Chinese (Simplified) [zh-CN]"

~\Applications\\Productivity\Notepad++.script at line ,Chinese,
should be -> ,TaiwaneseMandarin,

I am not sure maybe below is incorrect.
~\Applications\MultimediaIrfanViwe.script at lin 48:"ar-ye|Arabic.dll|zh-cn|bg-BG|Bulgarian.dll|Chinese_Simp.dll
maybe -> "ar-ye|Arabic.dll|bg-BG|Bulgarian.dll|zh-cn|Chinese_Simp.dll

**Comment by homes32** [comment]
Fixed! Thank you for reporting!
